run-webkit-tests: Don't crash when httpd is not installed
path_to_apache() in linux.py returns None when httpd is not present.
Check whether httpd_path is not void before using it.

TEST=Manually, after this patch run-webkit-tests http/* exits normally
instead of crashing with:
"AttributeError raised: 'NoneType' object has no attribute 'rfind'"

Review URL: https://codereview.chromium.org/1490073004

Cr-Commit-Position: refs/heads/master@{#362750}