Revert of [Telemetry] Fix video_unittest so that it actually runs on bots. (patchset #6 id:100001 of https://codereview.chromium.org/756553003/)
Reason for revert:
Looks like this broke telemetry_unittests
Build link:
https://build.chromium.org/p/chromium.linux/builders/Linux%20Tests/builds/17356

Output:
[284/694] telemetry.core.video_unittest.VideoTest.testFramesFromMp4 failed unexpectedly:
  Traceback (most recent call last):
    File "/mnt/data/b/build/slave/Linux_Tests/build/src/tools/telemetry/telemetry/decorators.py", line 84, in wrapper
      func(*args, **kwargs)
    File "/mnt/data/b/build/slave/Linux_Tests/build/src/tools/telemetry/telemetry/core/video_unittest.py", line 35, in testFramesFromMp4
      for i, timestamp_bitmap in enumerate(video_obj._FramesFromMp4()):
    File "/mnt/data/b/build/slave/Linux_Tests/build/src/tools/telemetry/telemetry/core/video.py", line 158, in _FramesFromMp4
      dimensions = GetDimensions(self._video_file_obj.name)
    File "/mnt/data/b/build/slave/Linux_Tests/build/src/tools/telemetry/telemetry/core/video.py", line 137, in GetDimensions
      output)
  AssertionError: Failed to determine video dimensions. output=avconv: error while loading shared libraries: libavdevice.so.53: cannot open shared object file: No such file or directory

Original issue's description:
> [Telemetry] Fix video_unittest so that it actually runs on bots.
>
> This also makes it explicitly clear that the avconv dependency is currently linux only.
>
> I had another CL out a while ago that fixes this, but that CL's blocked, so I'm separating this out.
>
> BUG=433943
>
> Committed: https://crrev.com/eae4959498c328f8e3fa710b1d507c0d68225b18
> Cr-Commit-Position: refs/heads/master@{#306858}

TBR=tonyg@chromium.org,slamm@chromium.org,mthiesse@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=433943

Review URL: https://codereview.chromium.org/748873003

Cr-Commit-Position: refs/heads/master@{#307024}