Revert "[android_webview] Hardcode the default text encoding to UTF-8."
Broke the release builder:

../third_party/android_webview_glue/src/chromium/java/com/android/webview/chromium/WebViewChromiumFactoryProvider.java:269:
error: cannot find symbol
        AwResource.setDefaultTextEncoding(

This reverts commit 846cb7cd02ce14b88905909f6b240b41099e3189.

Original description:

>   [android_webview] Hardcode the default text encoding to UTF-8.
>
>   The WebView will use a fixed default value for the text encoding instead
>   of getting it from the platform. This is in attempt to unify behavior
>   between devices.
>
>   BUG=422366
>   TBR=mkosiba@chromium.org
>
>   Review URL: https://codereview.chromium.org/639113004
>
>   Cr-Commit-Position: refs/heads/master@{#299287}
>   (cherry picked from commit 72ea36f782c38afb93387afe3cb6cf69ba9ab429)
>
>   Conflicts:
>     DEPS
>     android_webview/buildbot/aosp_manifest.xml
>     android_webview/renderer/aw_content_renderer_client.h
>     chrome/renderer/chrome_content_renderer_client.h
>
>   Review URL: https://codereview.chromium.org/655703003
>
>   Cr-Commit-Position: refs/branch-heads/2171@{#140}
>   Cr-Branched-From: 267aeeb8d85c8503a7fd12bd14654b8ea78d3974-refs/heads/master@{#297060}

BUG=424303
TBR=mkosiba@chromium.org

Review URL: https://codereview.chromium.org/654593003

Cr-Commit-Position: refs/branch-heads/2171@{#162}
Cr-Branched-From: 267aeeb8d85c8503a7fd12bd14654b8ea78d3974-refs/heads/master@{#297060}