[Temp] Backport r283541 from upstream.
This is another build fix for the WebRTC disabled case.

  content_renderer: Depend on libyuv even if WebRTC is not enabled.

  video_decoder_shim.cc uses libyuv, and the build fails if we're not
  building in component=shared_library mode and enable_webrtc=0:

  In file included from ../../third_party/libyuv/include/libyuv.h:15:0,
                   from ../../content/renderer/pepper/video_decoder_shim.cc:25:
  ../../third_party/libyuv/include/libyuv/compare.h:14:32: fatal error: libyuv/basic_types.h: No such file or directory
   #include "libyuv/basic_types.h"
                                  ^

  R=dmichael@chromium.org, bbudge@chromium.org

  Review URL: https://codereview.chromium.org/393813002