Remove unused private field device_position_
This fixes the error we encounter in M53
../../content/renderer/media/renderer_webaudiodevice_impl.h:94:25: error: private field 'device_position_' is not used
  media::StreamPosition device_position_;
                        ^