Revert of Fix InlineTextBox::characterWidths() not to measure every substring (patchset #1 id:1 of https://codereview.chromium.org/1919143005/ )
Reason for revert:
Broke the mac stable builder: https://uberchromegw.corp.google.com/i/official.desktop.continuous/builders/mac%20stable/builds/615

-----

Log output copied here for convenience:

../../third_party/WebKit/Source/core/layout/line/InlineTextBox.cpp:33:10: fatal error: 'platform/fonts/CharacterRange.h' file not found
#include "platform/fonts/CharacterRange.h"
         ^
1 error generated.
ninja: build stopped: subcommand failed.

Original issue's description:
> Fix InlineTextBox::characterWidths() not to measure every substring
>
> This patch changes InlineTextBox::characterWidths() to use
> Font::individualCharacterRanges() rather than to measure every
> substring of InlineTextBox. Measuring every substring without context
> is very expensive and also is not correct.
>
> When dev tools have long strings without spaces such as minified JS and
> accessbility is turned on, the measuring of substrings can almost hang
> it up.
>
> Currently, WebAXObject::characterOffsets() is the only user of this
> function.
>
> BUG=593679, 568032
> TEST=Existing tests cover, such as AutomationApiTest.BoundsForRange
>
> Review URL: https://codereview.chromium.org/1897853004
>
> Cr-Commit-Position: refs/heads/master@{#388162}
> (cherry picked from commit 11f1c680cca2250e01121b9bddd7bc6f8fb28a96)
>
> Committed: https://chromium.googlesource.com/chromium/src/+/a3b71a920f64013793487faebeadc648c1a0774b

TBR=kojii@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=593679, 568032

Review-Url: https://codereview.chromium.org/1927703002
Cr-Commit-Position: refs/branch-heads/2661@{#644}
Cr-Branched-From: ef6f6ae5e4c96622286b563658d5cd62a6cf1197-refs/heads/master@{#378081}