Revert of Update media notification when page title changes (patchset #25 id:570001 of https://codereview.chromium.org/1417743005/ )
Reason for revert:
Broke compile step on Android:

https://build.chromium.org/p/chromium.linux/builders/Android%20Builder/builds/59185/steps/compile/logs/stdio

Note: org.chromium.content.browser.test.NestedSystemMessageHandler accesses a declared method 'next()' dynamically
      Maybe this is library method 'android.database.CursorJoiner { android.database.CursorJoiner$Result next(); }'
      Maybe this is library method 'android.database.CursorJoiner { java.lang.Object next(); }'
      Maybe this is library method 'android.support.v4.media.session.IMediaSession { void next(); }'
      Maybe this is library method 'android.support.v4.media.session.IMediaSession$Stub$Proxy { void next(); }'
      Maybe this is library method 'android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase$MediaSessionStub { void next(); }'
      Maybe this is library method 'android.support.v4.util.MapCollections$ArrayIterator { java.lang.Object next(); }'
      Maybe this is library method 'android.support.v4.util.MapCollections$MapIterator { java.util.Map$Entry next(); }'
      Maybe this is library method 'android.support.v4.util.MapCollections$MapIterator { java.lang.Object next(); }'
      Maybe this is library method 'android.support.v7.util.MessageThreadUtil$MessageQueue { android.support.v7.util.MessageThreadUtil$SyncQueueItem next(); }'
      Maybe this is library method 'android.text.TextUtils$SimpleStringSplitter { java.lang.String next(); }'
      Maybe this is library method 'android.text.TextUtils$SimpleStringSplitter { java.lang.Object next(); }'
      Maybe this is library method 'com.google.android.gms.measurement.internal.a { java.lang.Object next(); }'
      Maybe this is library method 'java.sql.ResultSet { boolean next(); }'
      Maybe this is library method 'java.text.BreakIterator { int next(); }'
      Maybe this is library method 'java.text.CharacterIterator { char next(); }'
      Maybe this is library method 'java.text.CollationElementIterator { int next(); }'
      Maybe this is library method 'java.text.StringCharacterIterator { char next(); }'
      Maybe this is library method 'java.util.Iterator { java.lang.Object next(); }'
      Maybe this is library method 'java.util.ListIterator { java.lang.Object next(); }'
      Maybe this is library method 'java.util.Scanner { java.lang.String next(); }'
      Maybe this is library method 'java.util.Scanner { java.lang.Object next(); }'
      Maybe this is library method 'org.apache.http.message.BasicHeaderElementIterator { java.lang.Object next(); }'
      Maybe this is library method 'org.apache.http.message.BasicHeaderIterator { java.lang.Object next(); }'
      Maybe this is library method 'org.apache.http.message.BasicListHeaderIterator { java.lang.Object next(); }'
      Maybe this is library method 'org.apache.http.message.BasicTokenIterator { java.lang.Object next(); }'
      Maybe this is library method 'org.chromium.base.ObserverList$ObserverListIterator { java.lang.Object next(); }'
      Maybe this is library method 'org.chromium.chrome.browser.partnerbookmarks.PartnerBookmarksProviderIterator { org.chromium.chrome.browser.partnerbookmarks.PartnerBookmarksReader$Bookmark next(); }'
      Maybe this is library method 'org.chromium.chrome.browser.partnerbookmarks.PartnerBookmarksProviderIterator { java.lang.Object next(); }'
      Maybe this is library method 'org.chromium.chrome.browser.preferences.website.WebsitePermissionsFetcher$TaskQueue { void next(); }'
      Maybe this is library method 'org.json.JSONTokener { char next(); }'
      Maybe this is library method 'org.xmlpull.v1.XmlPullParser { int next(); }'
Note: the configuration refers to the unknown class 'com.google.ipc.invalidation.external.client2.contrib.AndroidListener$AlarmReceiver'
      Maybe you meant the fully qualified name 'com.google.ipc.invalidation.external.client.contrib.AndroidListener$AlarmReceiver'?
Note: there were 1 references to unknown classes.
      You should check your configuration for typos.
Note: there were 1 accesses to class members by means of introspection.
      You should consider explicitly keeping the mentioned class members
      (using '-keep' or '-keepclassmembers').
Note: there were 7 duplicate class definitions.
Warning: org.chromium.chrome.browser.sync.OpenTabsTest: can't find referenced method 'void loadUrlInNewTab(java.lang.String)' in class org.chromium.chrome.browser.sync.OpenTabsTest
Warning: there were 1 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile them and try again.
         Alternatively, you may have to specify the option
         '-dontskipnonpubliclibraryclassmembers'.
Error: Please correct the above warnings first.

Original issue's description:
> Update media notification when page title changes
>
> This CL makes the media notification keep in sync when the page title
> changes.
>
> BUG=550424
>
> Committed: https://crrev.com/d0b0d5fe705a29ff989dd3708d61154e8c600024
> Cr-Commit-Position: refs/heads/master@{#364938}

TBR=mlamouri@chromium.org,avayvod@chromium.org,tedchoc@chromium.org,zqzhang@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=550424

Review URL: https://codereview.chromium.org/1526433002

Cr-Commit-Position: refs/heads/master@{#364940}