Build fix in protected_media_identifier_permission_context.cc
Build failed due to uninitialied values.
../../chrome/browser/media/protected_media_identifier_permission_context.cc:187:8: error: 'persist' may be used uninitialized in this function [-Werror=maybe-uninitialized]
../../chrome/browser/media/protected_media_identifier_permission_context.cc:205:32: error: 'content_setting' may be used uninitialized in this function [-Werror=maybe-uninitialized]

Review URL: https://codereview.chromium.org/974223002

Cr-Commit-Position: refs/heads/master@{#319088}