Revert of Add support for multi-plane YUV format import into ArcGVDA and VAVDA. (patchset #4 id:160001 of https://codereview.chromium.org/2115453003/ )
Reason for revert:
Reverting for breaking Chromium Linux ChromeOS MSan

In file included from ../../chrome/gpu/gpu_arc_video_service.cc:5:
In file included from ../../chrome/gpu/gpu_arc_video_service.h:12:
../../chrome/gpu/arc_video_accelerator.h:134:38: error: no type named 'vector' in namespace 'std'
                          const std::vector<DmabufPlane>& dmabuf_planes) = 0;
                                ~~~~~^

https://build.chromium.org/p/chromium.memory.fyi/builders/Chromium%20Linux%20ChromeOS%20MSan%20Builder/builds/17540/steps/compile/logs/stdio

Original issue's description:
> Add support for multi-plane YUV format import into ArcGVDA and VAVDA.
>
> Add support for passing multiple strides and offsets along with a dmabuf
> to the ArcVideoAccelerator interface via AVA::BindDmabuf().
>
> Add support for importing YVU420 format to VAVDA and multi-plane pixmap
> import support to VaapiWrapper.
>
> TEST=video playback, crosvideo.appspot, vdatest
> BUG=b/29335168
>
> Committed: https://crrev.com/7f998dd741bb97b221e23122eccd273675b1a8a1
> Cr-Commit-Position: refs/heads/master@{#403991}

TBR=owenlin@chromium.org,kcwu@chromium.org,dcheng@chromium.org,posciak@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=b/29335168

Review-Url: https://codereview.chromium.org/2127783003
Cr-Commit-Position: refs/heads/master@{#404026}