Revert of Removed reprecated version of WebFrameClient::decidePolicyForNavigation (https://codereview.chromium.org/444163004/)
Reason for revert:
Broke Mac10.8 Tests.

http://build.chromium.org/p/chromium.webkit/builders/Mac10.8%20Tests/builds/9034

In file included from ../../mojo/services/html_viewer/html_document_view.cc:5:
../../mojo/services/html_viewer/html_document_view.h:48:38: error: 'mojo::HTMLDocumentView::decidePolicyForNavigation' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
  virtual blink::WebNavigationPolicy decidePolicyForNavigation(
                                     ^
../../third_party/WebKit/public/web/WebFrameClient.h:206:33: note: hidden overloaded virtual function 'blink::WebFrameClient::decidePolicyForNavigation' declared here: different number of parameters (1 vs 6)
    virtual WebNavigationPolicy decidePolicyForNavigation(const NavigationPolicyInfo& info) { return info.defaultPolicy; }
                                ^
1 error generated.

Original issue's description:
> Removed reprecated version of WebFrameClient::decidePolicyForNavigation
> 
> R=abarth
> BUG=
> 
> Committed: https://src.chromium.org/viewvc/blink?view=rev&revision=179774

TBR=abarth@chromium.org,oysteine@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=

Review URL: https://codereview.chromium.org/449303003

git-svn-id: svn://svn.chromium.org/blink/trunk@179775 bbb929c8-8fbe-4397-9dbb-9b2b20218538