Added const to DownloadItemIdCompare parameters
The DownloadItemIdCompare function was originally written to take
non-const pointers. This was presumably unintentional. This omission
means that const objects cannot be compared, and it breaks VS 2015
whose STL implementation prototypes the comparison path as taking const
objects.

The error is:

error C3848: expression having type
'const DownloadGroupNotification::DownloadItemIdCompare' would lose some
const-volatile qualifiers in order to call
'bool DownloadGroupNotification::DownloadItemIdCompare::operator ()'

The fix is simple and safe and appropriate and will unblock the VS
2015 builder.

The bug was introduced in https://codereview.chromium.org/1287803003

R=phajdan.jr@chromium.org
BUG=440500

Review URL: https://codereview.chromium.org/1298003002

Cr-Commit-Position: refs/heads/master@{#343816}