Revert of Fix assert in Flash component install. (patchset #1 id:1 of https://codereview.chromium.org/2109873002/ )
Reason for revert:
Compilation failure in Google Chrome Mac

https://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20Mac/builds/11620

Detailed message:

In file included from ../../base/bind_internal.h:13:
../../base/bind_helpers.h:412:7: error: implicit instantiation of undefined template 'base::internal::DropTypeListItemImpl<1, base::internal::TypeList<> >'
    : DropTypeListItemImpl<n - 1, TypeList<List...>> {};
      ^
../../base/bind_helpers.h:426:1: note: in instantiation of template class 'base::internal::DropTypeListItemImpl<2, base::internal::TypeList<component_updater::ComponentUpdateService *> >' requested here
using DropTypeListItem = typename DropTypeListItemImpl<n, List>::Type;
^
../../base/bind_internal.h:395:23: note: in instantiation of template type alias 'DropTypeListItem' requested here
  using UnboundArgs = DropTypeListItem<sizeof...(BoundArgs), Args>;
                      ^
../../base/bind_internal.h:437:1: note: in instantiation of template class 'base::internal::MakeUnboundRunTypeImpl<void (*)(component_updater::ComponentUpdateService *), const base::FilePath &, const base::Version &>' requested here
using MakeUnboundRunType =
^
../../base/bind.h:50:23: note: in instantiation of template type alias 'MakeUnboundRunType' requested here
inline base::Callback<MakeUnboundRunType<Functor, Args...>>
                      ^
../../chrome/browser/component_updater/pepper_flash_component_installer.cc:113:7: note: while substituting deduced template arguments into function template 'Bind' [with Functor = void (*)(component_updater::ComponentUpdateService *), Args = <const base::FilePath &, const base::Version &>]
      base::Bind(&RegisterPepperFlashWithChrome, path, version));
      ^
../../base/bind_helpers.h:407:8: note: template is declared here
struct DropTypeListItemImpl;
       ^
../../base/bind_helpers.h:480:1: error: implicit instantiation of undefined template 'base::internal::MakeFunctionTypeImpl<void, int>'
using MakeFunctionType = typename MakeFunctionTypeImpl<R, ArgList>::Type;
^
../../base/bind_internal.h:396:16: note: in instantiation of template type alias 'MakeFunctionType' requested here
  using Type = MakeFunctionType<ReturnType, UnboundArgs>;
               ^
../../base/bind_internal.h:437:1: note: in instantiation of template class 'base::internal::MakeUnboundRunTypeImpl<void (*)(component_updater::ComponentUpdateService *), const base::FilePath &, const base::Version &>' requested here
using MakeUnboundRunType =
^
../../base/bind.h:50:23: note: in instantiation of template type alias 'MakeUnboundRunType' requested here
inline base::Callback<MakeUnboundRunType<Functor, Args...>>
                      ^
../../chrome/browser/component_updater/pepper_flash_component_installer.cc:113:7: note: while substituting deduced template arguments into function template 'Bind' [with Functor = void (*)(component_updater::ComponentUpdateService *), Args = <const base::FilePath &, const base::Version &>]
      base::Bind(&RegisterPepperFlashWithChrome, path, version));
      ^
../../base/bind_helpers.h:468:8: note: template is declared here
struct MakeFunctionTypeImpl;
       ^
../../chrome/browser/component_updater/pepper_flash_component_installer.cc:113:19: error: use of undeclared identifier 'RegisterPepperFlashWithChrome'
      base::Bind(&RegisterPepperFlashWithChrome, path, version));
                  ^
3 errors generated.

Original issue's description:
> Fix assert in Flash component install.
>
> BUG=
>
> Committed: https://crrev.com/df973871410891db6f94d224327d8c7cb4b8ae1e
> Cr-Commit-Position: refs/heads/master@{#403218}

TBR=sorin@chromium.org,waffles@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=

Review-Url: https://codereview.chromium.org/2114753002
Cr-Commit-Position: refs/heads/master@{#403233}