Revert of Make a mojo:apptests GN meta-target, add apptests. (patchset #3 id:60001 of https://codereview.chromium.org/1050233005/)
Reason for revert:
Caused compile failures (many errors, one example below) on Mac GN bot:
http://build.chromium.org/p/chromium.mac/builders/Mac%20GN/builds/7019/steps/compile/logs/stdio

gen/mojo/services/html_viewer/blink_resource_map.h:37:58:error: no newline at end of file [-Werror,-Wnewline-eof]
#endif // MOJO_SERVICES_HTML_VIEWER_BLINK_RESOURCE_MAP_H_

Original issue's description:
> Make a mojo:apptests GN meta-target, add apptests.
>
> Add an apptest meta-target in mojo/BUILD.gn.
> Move the apptests targets specified in src/BUILD.gn.
> Add the remaining apptest targets (clipboard, VM, WM).
>
> Was limited to release, allow debug, but exclude component.
> See gn_debug compile error from including component build in PS2:
>   FAILED: /b/build/slave/linux_chromium_gn/build/src/buildtools/linux64/gn --root=/b/build/slave/linux_chromium_gn/build/src -q gen //out/Debug/
>   ERROR at //mojo/shell/BUILD.gn:13:1: Assertion failed.
>   assert(!is_component_build)
>
> BUG=NONE
> TEST=Building mojo:apptests builds all local apptest binaries (on dbg too!).
> R=sky@chromium.org
> TBR=ben@chromium.org
>
> Committed: https://crrev.com/16b112790f541670d5f2ab97dfa70c8b89b44b1f
> Cr-Commit-Position: refs/heads/master@{#325570}

TBR=sky@chromium.org,ben@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=NONE

Review URL: https://codereview.chromium.org/1093763002

Cr-Commit-Position: refs/heads/master@{#325575}