Revert "Add a new app API to enable watchdog behavior restarts in kiosk apps"
This reverts commit 6c1c80d89c29b22117b13760643c7fd1734e2466.

This change was reverted because it fails under DrMemory. First failing
build is:

https://build.chromium.org/p/chromium.memory.fyi/builders/Windows%20Unit%20%28DrMemory%20full%29%20%285%29/builds/7514

Sample failure output:
RestartAfterDelayApiTest.RestartAfterDelayTest:
c:\b\build\slave\drm-cr\build\src\extensions\browser\api\runtime\restart_after_delay_api_unittest.cc(230):
error: The difference between (desired_restart_time() -
last_restart_time).InSecondsF() and
base::TimeDelta::FromSeconds(2).InSecondsF() is 0.025495000000000045,
which exceeds 0.01, where
(desired_restart_time() - last_restart_time).InSecondsF() evaluates to
1.974505,
base::TimeDelta::FromSeconds(2).InSecondsF() evaluates to 2, and
0.01 evaluates to 0.01.

TBR=afakhry@chromium.org
BUG=604578

Review-Url: https://codereview.chromium.org/2070753003
Cr-Commit-Position: refs/heads/master@{#400136}