Revert of Roll ANGLE. (patchset #2 id:20001 of https://codereview.chromium.org/1141753002/)
Reason for revert:
broke linux gn build

../../third_party/angle/src/libANGLE/Display.cpp:113:24:error: no type named 'DisplayGLX' in namespace 'rx'
        impl = new rx::DisplayGLX();
                   ~~~~^
1 error generated.
ninja: build stopped: subcommand failed.

http://build.chromium.org/p/chromium.linux/builders/Linux%20GN%20Clobber/builds/190/steps/compile/logs/stdio

Original issue's description:
> Roll ANGLE.
>
> https://chromium.googlesource.com/angle/angle/+log/b11e24..71632d
>
> BUG=484963
> BUG=483252
>
> Committed: https://crrev.com/6e8e29564f8590bff2215668d959b17075b96240
> Cr-Commit-Position: refs/heads/master@{#329727}

TBR=jmadill@chromium.org,geofflang@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=484963

Review URL: https://codereview.chromium.org/1128913010

Cr-Commit-Position: refs/heads/master@{#329741}