options: fix closure compilation issue.
## (ERROR) Error in: options_bundle.js
## /mnt/data/b/build/slave/Closure_Compilation_Linux/build/src/chrome/browser/resources/options/browser_options.js:1514: ERROR - actual parameter 1 of options.BrowserOptions.prototype.enableElementIfPossible_ does not match formal parameter
## found   : (HTMLElement|null)
## required: Element
##         this.enableElementIfPossible_($('set-wallpaper'));
##                                       ^

TBR=michaelpg@chromium.org
BUG=393873

Review URL: https://codereview.chromium.org/657013002

Cr-Commit-Position: refs/heads/master@{#299638}