De-inline the titlebar methods in ui::views::ViewsDelegate.
Having ShouldShowTitleBar() and SetShouldShowTitleBar() inline in the
class declaration breaks the build with Chromium's clang:

../../ui/views/views_delegate.h:152:59: error: [chromium-style] virtual methods with non-empty bodies shouldn't be declared inline.
../../ui/views/views_delegate.h:155:43: error: [chromium-style] virtual methods with non-empty bodies shouldn't be declared inline.