Revert of Add size check for PaintLayer (patchset #4 id:60001 of https://codereview.chromium.org/1616193002/ )
Reason for revert:
"Chromium Webkit WebKit Linux Oilpan Builder failure"

https://build.chromium.org/p/chromium.webkit/builders/WebKit%20Linux%20Oilpan%20Builder/builds/917/steps/compile/logs/stdio

../../third_party/WebKit/Source/core/paint/PaintLayer.cpp:125:1: error: static_assert failed "PaintLayer should stay small"
static_assert(sizeof(PaintLayer) == sizeof(SameSizeAsPaintLayer), "PaintLayer should stay small");

Original issue's description:
> Add size check for PaintLayer
>
> Committed: https://crrev.com/da42a3f1bb4756fb35f7ce4f90064f29eee87946
> Cr-Commit-Position: refs/heads/master@{#371103}

TBR=chrishtr@chromium.org,wangxianzhu@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/1622593003

Cr-Commit-Position: refs/heads/master@{#371111}