Don't try to dllexport InkDropAnimationControllerStub
It's in an anonymous namespace, so it cannot be exported, and this causes
an error on the Win-Clang bots:

..\..\ui\views\animation\ink_drop_animation_controller_factory.cc(20,20) :
  error: 'views::(anonymous namespace)::InkDropAnimationControllerStub'
  must have external linkage when declared 'dllexport'

  class VIEWS_EXPORT InkDropAnimationControllerStub
                     ^

I'm pretty sure this class was never intended to be exported.

BUG=82385
TBR=bruthig,sadrul

Review URL: https://codereview.chromium.org/1302913002

Cr-Commit-Position: refs/heads/master@{#344511}