Revert of [clang] Enable compilation of compiler runtime for iOS simulator. (patchset #2 id:20001 of https://codereview.chromium.org/1883723003/ )
Reason for revert:
Breaks clang tot bots:

https://build.chromium.org/p/chromium.fyi/builders/ClangToTMac/builds/8735

[3388/3417] Building CXX object lib/tsan/CMakeFiles/clang_rt.tsan_osx_dynamic.dir/rtl/tsan_interface_ann.cc.o
FAILED: /Applications/Xcode7.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -Dclang_rt_tsan_iossim_dynamic_EXPORTS -DLLVM_FORCE_HEAD_REVISION -Wall -std=c++11 -O3 -DNDEBUG -arch x86_64 -isysroot /Applications/Xcode7.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -fPIC -I/b/build/slave/ClangToTMac/build/src/third_party/llvm/compiler-rt/lib/tsan/..     -stdlib=libc++ -miphoneos-version-min=7.0 -isysroot /Applications/Xcode7.0.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -fPIC -fno-builtin -fno-exceptions -fomit-frame-pointer -funwind-tables -fno-stack-protector -fvisibility=hidden -fvisibility-inlines-hidden -fno-function-sections -fno-lto -O3 -gline-tables-only -Wno-gnu -Wno-variadic-macros -Wno-c99-extensions -Wno-non-virtual-dtor -fPIE -fno-rtti -msse3 -Wframe-larger-than=512 -Wglobal-constructors -MMD -MT lib/tsan/CMakeFiles/clang_rt.tsan_iossim_dynamic.dir/rtl/tsan_interceptors_mac.cc.o -MF lib/tsan/CMakeFiles/clang_rt.tsan_iossim_dynamic.dir/rtl/tsan_interceptors_mac.cc.o.d -o lib/tsan/CMakeFiles/clang_rt.tsan_iossim_dynamic.dir/rtl/tsan_interceptors_mac.cc.o -c /b/build/slave/ClangToTMac/build/src/third_party/llvm/compiler-rt/lib/tsan/rtl/tsan_interceptors_mac.cc
/b/build/slave/ClangToTMac/build/src/third_party/llvm/compiler-rt/lib/tsan/rtl/tsan_interceptors_mac.cc:24:10: fatal error: 'xpc/xpc.h' file not found
#include <xpc/xpc.h>
         ^

Maybe that file shouldn't be built in iOS builds? Looks like some upstream build config problem; for now revert to get our bots back green.

Original issue's description:
> [clang] Enable compilation of compiler runtime for iOS simulator.
>
> This is required to enable ASan and coverage on simulators (and
> other tools like UBSan, TSan, ...).
>
> BUG=450379,602649
>
> Committed: https://crrev.com/d957e66e8df2c23d18b9ef64a06088c1b6578fc3
> Cr-Commit-Position: refs/heads/master@{#387832}

TBR=sdefresne@chromium.org
# Not skipping CQ checks because original CL landed more than 1 days ago.
BUG=450379,602649

Review URL: https://codereview.chromium.org/1893353002

Cr-Commit-Position: refs/heads/master@{#387914}