Revert of Add support for new calls in cryptohome (part 2) (https://codereview.chromium.org/198003002/)
Reason for revert:
Breaks compilation on Linux ChromiumOS Builder

[895/1749] CXX obj/chrome/browser/ui/browser_ui.auto_login_infobar_delegate.o
FAILED: c++ -MMD -MF obj/chrome/browser/chromeos/login/cryptohome/browser_chromeos.homedir_methods.o.d -DV8_DEPRECATION_WARNINGS -DBLINK_SCALE_FILTERS_AT_RECORD_TIME -D_FILE_OFFSET_BITS=64 -DCHROMIUM_BUILD -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_X11=1 -DOS_CHROMEOS=1 -DUSE_XI2_MT=2 -DIMAGE_LOADER_EXTENSION=1 -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_INPUT_SPEECH -DENABLE_NOTIFICATIONS -DENABLE_HIDPI=1 -DENABLE_NEW_GAMEPAD_API=1 -DUSE_UDEV -DENABLE_EGLIMAGE=1 -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_AUTOMATION=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_FULL_PRINTING=1 -DENABLE_PRINTING=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_MANAGED_USERS=1 -DENABLE_MDNS=1 -DNACL_WINDOWS=0 -DNACL_LINUX=1 -DNACL_OSX=0 -DNACL_TARGET_SUBARCH=64 -DNACL_TARGET_ARCH=x86 -DNACL_BUILD_SUBARCH=64 -DNACL_BUILD_ARCH=x86 -DGL_GLEXT_PROTOTYPES -DUSE_BRLAPI -DSK_ENABLE_INST_COUNT=0 -DSK_SUPPORT_GPU=1 '-DGR_GL_CUSTOM_SETUP_HEADER="GrGLConfig_chrome.h"' -DSK_ENABLE_LEGACY_API_ALIASING=1 -DSK_ATTR_DEPRECATED=SK_NOTHING_ARG1 -DGR_GL_IGNORE_ES3_MSAA=0 -DSK_SUPPORT_LEGACY_LAYERRASTERIZER_API=1 -DSK_WILL_NEVER_DRAW_PERSPECTIVE_TEXT -DSK_SUPPORT_LEGACY_COMPATIBLEDEVICE_CONFIG=1 -DSK_SUPPORT_LEGACY_PUBLICEFFECTCONSTRUCTORS=1 -DSK_SUPPORT_LEGACY_WRITEPIXELSCONFIG -DSK_SUPPORT_LEGACY_GETCLIPTYPE -DSK_SUPPORT_LEGACY_GETTOTALCLIP -DSK_SUPPORT_LEGACY_GETTOPDEVICE -DSK_USE_POSIX_THREADS -DSK_DEFERRED_CANVAS_USES_FACTORIES=1 -DHUNSPELL_STATIC -DHUNSPELL_CHROME_CLIENT -DUSE_HUNSPELL -DU_USING_ICU_NAMESPACE=0 -DU_STATIC_IMPLEMENTATION -DFEATURE_ENABLE_SSL -DFEATURE_ENABLE_VOICEMAIL -DEXPAT_RELATIVE_PATH -DGTEST_RELATIVE_PATH -DNO_MAIN_THREAD_WRAPPING -DNO_SOUND_SYSTEM -DLINUX -DPOSIX -DCHROMEOS -DLIBXML_STATIC -DPROTOBUF_USE_DLLS -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DUSE_NSS=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -D_FORTIFY_SOURCE=2 -Igen -I../../breakpad/src -Iobj/chrome/browser_chromeos.gen -Iobj/chrome/browser_chromeos.gen/chrome -I../../third_party/khronos -I../../gpu -I../.. -I../../skia/config -I../../third_party/WebKit/Source -Igen/protoc_out -Igen/chrome -I../../third_party/re2 -Igen/policy -Igen/components/strings -I../../net/third_party/nss/ssl -I../../third_party/skia/src/core -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/pdf -I../../third_party/skia/include/gpu -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../skia/ext -I../../third_party/cacheinvalidation/overrides -I../../third_party/cacheinvalidation/src -I../../third_party/cacheinvalidation/google/cacheinvalidation -I../../third_party/icu/source/i18n -I../../third_party/icu/source/common -I../../third_party/leveldatabase/src/include -I../../third_party/leveldatabase/src -I../../third_party/leveldatabase -I../../third_party/libjingle/overrides -I../../third_party/libjingle/source -I../../testing/gtest/include -I../../third_party -I../../third_party/webrtc -I../../third_party/libusb/src/libusb -I../../third_party/libxml/linux/include -I../../third_party/libxml/src/include -I../../third_party/npapi -I../../third_party/npapi/bindings -I../../third_party/protobuf -I../../third_party/protobuf/src -I../../third_party/zlib -Igen/ui/app_locale_settings -Igen/ui/ui_strings -Igen/ui/ui_resources -I../../v8/include -Igen/webkit -Igen/ash/ash_resources -Igen/ash_strings -Igen/ui/gl -I../../third_party/mesa/src/include -Werror -pthread -fno-exceptions -fno-strict-aliasing -Wall -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/nss -I/usr/include/nspr -Wno-unknown-pragmas -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -Wsign-compare  -c ../../chrome/browser/chromeos/login/cryptohome/homedir_methods.cc -o obj/chrome/browser/chromeos/login/cryptohome/browser_chromeos.homedir_methods.o
../../chrome/browser/chromeos/login/cryptohome/homedir_methods.cc: In function 'cryptohome::MountError cryptohome::{anonymous}::MapError(cryptohome::CryptohomeErrorCode)':
../../chrome/browser/chromeos/login/cryptohome/homedir_methods.cc:95:1: error: control reaches end of non-void function [-Werror=return-type]
cc1plus: all warnings being treated as errors
ninja: build stopped: subcommand failed.


Original issue's description:
> Add support for new calls in cryptohome.
> 
> Related changes on chromeos side:
> 
> https://chromium-review.googlesource.com/#/c/186561/
> https://chromium-review.googlesource.com/#/c/188490/
> 
> New methods added: MountEx, CheckKeyEx, AddKeyEx, UpdateKeyEx (extended versions of Mount, CheckKey, AddKey calls).
> 
> This is done to achieve several goals. One is to unify most of cryptohome calls by using protobuffers.
> Using protobuffers also makes most of the code resilient to implementation changes.
> These methods also introduce key annotations (labels), that are used to specify keys for operations on valuts with multiple keys, as well as introduce per-key privileges.
> 
> First part of CL: https://chromiumcodereview.appspot.com/186663002/
> NOTRY=true
> as it only adds code.
> BUG=244472
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=256823

TBR=nkostylev@chromium.org,antrim@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=244472

Review URL: https://codereview.chromium.org/197753007

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@256824 0039d316-1c4b-4281-b951-d872f2087c98