Revert "Revert "Replace WebAudio MediaCodec usage with FFmpeg" commit"
This reverts commit 747cccaf636449ea9ba0a2dba4cbad7b79d87f96. This
change broke dozens of Android device tests:
<https://build.crosswalk-project.org/builders/Crosswalk%20Tests%20%28Android%20x86%29/builds/2197>

> W/System.err(12787): java.lang.NoClassDefFoundError: org/chromium/media/WebAudioMediaCodecBridge
> W/System.err(12787):    at java.lang.Runtime.nativeLoad(Native Method)
> W/System.err(12787):    at java.lang.Runtime.loadLibrary(Runtime.java:369)
> W/System.err(12787):    at java.lang.System.loadLibrary(System.java:535)
> W/System.err(12787):    at org.xwalk.core.internal.XWalkViewDelegate.loadXWalkLibrary(XWalkViewDelegate.java:167)
> W/System.err(12787):    at java.lang.reflect.Method.invokeNative(Native Method)
> W/System.err(12787):    at java.lang.reflect.Method.invoke(Method.java:511)
> W/System.err(12787):    at org.xwalk.core.ReflectMethod.invoke(ReflectMethod.java:61)
> W/System.err(12787):    at org.xwalk.core.XWalkCoreWrapper.checkCoreArchitecture(XWalkCoreWrapper.java:346)
> W/System.err(12787):    at org.xwalk.core.XWalkCoreWrapper.findSharedCore(XWalkCoreWrapper.java:262)
> W/System.err(12787):    at org.xwalk.core.XWalkCoreWrapper.attachXWalkCore(XWalkCoreWrapper.java:183)
> W/System.err(12787):    at org.xwalk.core.XWalkLibraryLoader$ActivateTask.doInBackground(XWalkLibraryLoader.java:335)
> W/System.err(12787):    at org.xwalk.core.XWalkLibraryLoader$ActivateTask.doInBackground(XWalkLibraryLoader.java:317)
> W/System.err(12787):    at android.os.AsyncTask$2.call(AsyncTask.java:288)
> W/System.err(12787):    at java.util.concurrent.FutureTask.run(FutureTask.java:234)
> W/System.err(12787):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
> W/System.err(12787):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1094)
> W/System.err(12787):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:579)
> W/System.err(12787):    at java.lang.Thread.run(Thread.java:871)
> W/System.err(12787): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.chromium.media.WebAudioMediaCodecBridge" on path: /data/app/org.xwalk.core-1.apk
> W/System.err(12787):    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
> W/System.err(12787):    at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
> W/System.err(12787):    at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
> W/System.err(12787):    ... 18 more
> F/chromium(12787): [0602/050445:FATAL:jni_android.cc(123)] Failed to find class org/chromium/media/WebAudioMediaCodecBridge

BUG=XWALK-7307