Revert of [Sync] Removing SYNC_EXPORT_PRIVATE macro and fixing lint violations on (patchset #3 id:40001 of https://codereview.chromium.org/1509563002/ )
Reason for revert:
Fails to compile for IOS

https://build.chromium.org/p/chromium.mac/builders/iOS_Device/builds/30956/steps/compile/logs/stdio

CompileC /b/build/slave/iOS_Device/build/src/xcodebuild/sync.build/Release-iphoneos/attachment_store_proto.build/Objects-normal/armv7/attachment_store.pb.o /b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.cc normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler
    cd /b/build/slave/iOS_Device/build/src/sync
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode7.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode7.0.app/Contents/Developer/usr/bin:/Users/chrome-bot/slavebin:/b/depot_tools:/usr/local/git/bin:/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
    /b/build/slave/iOS_Device/build/src/sync/../third_party/llvm-build/Release+Asserts/bin/clang -x c++ -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c++11 -stdlib=libc++ -Wno-trigraphs -fno-exceptions -fno-rtti -Os -Werror -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wnewline-eof -Wno-c++11-extensions -DV8_DEPRECATION_WARNINGS -DCLD_VERSION=2 -DDISABLE_NACL -DCHROMIUM_BUILD -DCR_CLANG_REVISION=254049-1 -DUSE_LIBJPEG_TURBO=1 -DDONT_EMBED_BUILD_METADATA -DFIELDTRIAL_TESTING_ENABLED -DDISABLE_FTP_SUPPORT=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DSYNC_IMPLEMENTATION -DPROTOBUF_USE_DLLS -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DUSE_LIBPCI=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DNS_BLOCK_ASSERTIONS=1 -D_FORTIFY_SOURCE=2 -isysroot /Applications/Xcode7.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -miphoneos-version-min=7.0 -g -fvisibility=hidden -fvisibility-inlines-hidden -fno-threadsafe-statics -Wno-sign-conversion -I/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos/include -I/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release -I/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out -I.. -I../third_party/protobuf -I../third_party/protobuf/src -I/b/build/slave/iOS_Device/build/src/xcodebuild/sync.build/Release-iphoneos/attachment_store_proto.build/DerivedSources/armv7 -I/b/build/slave/iOS_Device/build/src/xcodebuild/sync.build/Release-iphoneos/attachment_store_proto.build/DerivedSources -Wall -Wendif-labels -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-selector-type-mismatch -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-inconsistent-missing-override -Wno-shift-negative-value -Wno-bitfield-width -Wexit-time-destructors -F/b/build/slave/iOS_Device/build/src/xcodebuild/Release-iphoneos -Xclang -load -Xclang /b/build/slave/iOS_Device/build/src/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.dylib -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-templates -Xclang -plugin-arg-find-bad-constructs -Xclang enforce-overriding-blink -MMD -MT dependencies -MF /b/build/slave/iOS_Device/build/src/xcodebuild/sync.build/Release-iphoneos/attachment_store_proto.build/Objects-normal/armv7/attachment_store.pb.d --serialize-diagnostics /b/build/slave/iOS_Device/build/src/xcodebuild/sync.build/Release-iphoneos/attachment_store_proto.build/Objects-normal/armv7/attachment_store.pb.dia -c /b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.cc -o /b/build/slave/iOS_Device/build/src/xcodebuild/sync.build/Release-iphoneos/attachment_store_proto.build/Objects-normal/armv7/attachment_store.pb.o
In file included from /b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.cc:5:
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:34:6: error: variable has incomplete type 'void'
void SYNC_EXPORT_PRIVATE protobuf_AddDesc_attachment_5fstore_2eproto();
     ^
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:34:25: error: expected ';' after top level declarator
void SYNC_EXPORT_PRIVATE protobuf_AddDesc_attachment_5fstore_2eproto();
                        ^
                        ;
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:46:1: error: unknown type name 'SYNC_EXPORT_PRIVATE'
SYNC_EXPORT_PRIVATE bool RecordMetadata_Component_IsValid(int value);
^
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:46:21: error: expected unqualified-id
SYNC_EXPORT_PRIVATE bool RecordMetadata_Component_IsValid(int value);
                    ^
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:53:27: error: variable has incomplete type 'class SYNC_EXPORT_PRIVATE'
class SYNC_EXPORT_PRIVATE StoreMetadata : public ::google::protobuf::MessageLite {
                          ^
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:53:7: note: forward declaration of 'attachment_store_pb::SYNC_EXPORT_PRIVATE'
class SYNC_EXPORT_PRIVATE StoreMetadata : public ::google::protobuf::MessageLite {
      ^
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:53:41: error: expected ';' after top level declarator
class SYNC_EXPORT_PRIVATE StoreMetadata : public ::google::protobuf::MessageLite {
                                        ^
                                        ;
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:53:43: error: expected unqualified-id
class SYNC_EXPORT_PRIVATE StoreMetadata : public ::google::protobuf::MessageLite {
                                          ^
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:146:27: error: variable has incomplete type 'class SYNC_EXPORT_PRIVATE'
class SYNC_EXPORT_PRIVATE RecordMetadata : public ::google::protobuf::MessageLite {
                          ^
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:53:7: note: forward declaration of 'attachment_store_pb::SYNC_EXPORT_PRIVATE'
class SYNC_EXPORT_PRIVATE StoreMetadata : public ::google::protobuf::MessageLite {
      ^
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:146:42: error: expected ';' after top level declarator
class SYNC_EXPORT_PRIVATE RecordMetadata : public ::google::protobuf::MessageLite {
                                         ^
                                         ;
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:146:44: error: expected unqualified-id
class SYNC_EXPORT_PRIVATE RecordMetadata : public ::google::protobuf::MessageLite {
                                           ^
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:280:13: error: incomplete type 'attachment_store_pb::StoreMetadata' named in nested name specifier
inline bool StoreMetadata::has_schema_version() const {
            ^~~~~~~~~~~~~~~
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:38:7: note: forward declaration of 'attachment_store_pb::StoreMetadata'
class StoreMetadata;
      ^
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:283:13: error: incomplete type 'attachment_store_pb::StoreMetadata' named in nested name specifier
inline void StoreMetadata::set_has_schema_version() {
            ^~~~~~~~~~~~~~~
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:38:7: note: forward declaration of 'attachment_store_pb::StoreMetadata'
class StoreMetadata;
      ^
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:286:13: error: incomplete type 'attachment_store_pb::StoreMetadata' named in nested name specifier
inline void StoreMetadata::clear_has_schema_version() {
            ^~~~~~~~~~~~~~~
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:38:7: note: forward declaration of 'attachment_store_pb::StoreMetadata'
class StoreMetadata;
      ^
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:289:13: error: incomplete type 'attachment_store_pb::StoreMetadata' named in nested name specifier
inline void StoreMetadata::clear_schema_version() {
            ^~~~~~~~~~~~~~~
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:38:7: note: forward declaration of 'attachment_store_pb::StoreMetadata'
class StoreMetadata;
      ^
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:293:34: error: incomplete type 'attachment_store_pb::StoreMetadata' named in nested name specifier
inline ::google::protobuf::int32 StoreMetadata::schema_version() const {
                                 ^~~~~~~~~~~~~~~
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:38:7: note: forward declaration of 'attachment_store_pb::StoreMetadata'
class StoreMetadata;
      ^
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:296:13: error: incomplete type 'attachment_store_pb::StoreMetadata' named in nested name specifier
inline void StoreMetadata::set_schema_version(::google::protobuf::int32 value) {
            ^~~~~~~~~~~~~~~
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:38:7: note: forward declaration of 'attachment_store_pb::StoreMetadata'
class StoreMetadata;
      ^
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:306:13: error: incomplete type 'attachment_store_pb::RecordMetadata' named in nested name specifier
inline bool RecordMetadata::has_attachment_size() const {
            ^~~~~~~~~~~~~~~~
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:39:7: note: forward declaration of 'attachment_store_pb::RecordMetadata'
class RecordMetadata;
      ^
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:309:13: error: incomplete type 'attachment_store_pb::RecordMetadata' named in nested name specifier
inline void RecordMetadata::set_has_attachment_size() {
            ^~~~~~~~~~~~~~~~
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:39:7: note: forward declaration of 'attachment_store_pb::RecordMetadata'
class RecordMetadata;
      ^
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:312:13: error: incomplete type 'attachment_store_pb::RecordMetadata' named in nested name specifier
inline void RecordMetadata::clear_has_attachment_size() {
            ^~~~~~~~~~~~~~~~
/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/protoc_out/sync/internal_api/attachments/proto/attachment_store.pb.h:39:7: note: forward declaration of 'attachment_store_pb::RecordMetadata'
class RecordMetadata;
      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

Original issue's description:
> [Sync] Removing SYNC_EXPORT_PRIVATE macro and fixing lint violations on
> all touched files.
>
> BUG=554242,567301
>
> Committed: https://crrev.com/1621aa930169650b0c4c371e743f3be58a70abae
> Cr-Commit-Position: refs/heads/master@{#363603}

TBR=zea@chromium.org,skym@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=554242,567301

Review URL: https://codereview.chromium.org/1503253004

Cr-Commit-Position: refs/heads/master@{#363609}