Fix crash when sorting WebsitePreferences.
Website.compareByStorageTo() had an error where it would return -1
(instead of 0) when comparing two websites with the same amount of
storage. As a result, Collections.sort() would sometimes throw an
exception: "Comparison method violates its general contract!".

This fixes that bug and introduces MathUtils.compareLongs() to prevent
similar errors in other parts of the codebase. A follow-up CL will use
this method in more places.

Note: it's possible there are other bugs in the compareTo() method. I'll
monitor the crash reports after landing this to see if more bugs need
fixing.

BUG=486884

Review URL: https://codereview.chromium.org/1184163006

Cr-Commit-Position: refs/heads/master@{#334583}
(cherry picked from commit 4cc42e390ac39d9799070d75fa6bef3ec5ac991f)

Review URL: https://codereview.chromium.org/1188823004.

Cr-Commit-Position: refs/branch-heads/2403@{#327}
Cr-Branched-From: f54b8097a9c45ed4ad308133d49f05325d6c5070-refs/heads/master@{#330231}