Revert of  Clean up public interface of AttachmentBrokerUnprivileged. (patchset #4 id:80001 of https://codereview.chromium.org/1679763002/ )
Reason for revert:
c:\b\build\slave\win\build\src\remoting\host\remoting_me2me_host.cc(937) : error C2065: 'attachment_broker_' : undeclared identifier

http://build.chromium.org/p/chromium/builders/Win/builds/40168

Original issue's description:
> Clean up public interface of AttachmentBrokerUnprivileged.
>
> In the old interface, a static factory method returns a scoped_ptr, and the
> caller had to manage the lifetime. Since this is a global object with minimal
> memory footprint, and is required to outlive every IPC::Channel, it's much
> easier for the global to never be destroyed. This also matches the interface for
> AttachmentBrokerPrivileged.
>
> BUG=584297

TBR=tsepez@chromium.org,avi@chromium.org,mseaborn@chromium.org,sergeyu@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=584297

Review URL: https://codereview.chromium.org/1688433005

Cr-Commit-Position: refs/heads/master@{#374771}