Componentization: make MultiColumnFragmentainerGroupList visible.
To add default constructor, modify MultiColumnFragmentainerGroup to use
a pointer instead of a reference:
third_party\webkit\source\wtf\vector.h(103) : error C2512: 'blink::MultiColumnFragmentainerGroup' : no appropriate default constructor available
  third_party\webkit\source\wtf\vector.h(101) : while compiling class template member function 'void WTF::VectorInitializer<false,T>::initialize(T *,T *)'
  with
  [
     T=blink::MultiColumnFragmentainerGroup
  ]

BUG=358074

Review URL: https://codereview.chromium.org/1064363002

git-svn-id: svn://svn.chromium.org/blink/trunk@193415 bbb929c8-8fbe-4397-9dbb-9b2b20218538