Revert of Revert of Roll WebRTC 8649:8651, Libjingle 8639:8651 (patchset #1 id:1 of https://codereview.chromium.org/989253002/)
Reason for revert:
The compile error was not caused by the WebRTC roll.

Original issue's description:
> Revert of Roll WebRTC 8649:8651, Libjingle 8639:8651 (patchset #1 id:1 of https://codereview.chromium.org/987033002/)
>
> Reason for revert:
> Broke compilation on Linux http://build.chromium.org/p/chromium/builders/Linux/builds/59264 with error message: AttributeError: 'Checker' object has no attribute 'run_js_check'
>
> Original issue's description:
> > Roll WebRTC 8649:8651, Libjingle 8639:8651
> >
> > WebRTC 8649:8651
> > Changes: https://chromium.googlesource.com/external/webrtc/trunk/webrtc.git/+log/b4c07a0..61b3feb
> >
> > Libjingle 8639:8651
> > Changes: https://chromium.googlesource.com/external/webrtc/trunk/talk.git/+log/c9f4c13..4138f65
> >
> > TBR=tommi
> >
> > Committed: https://crrev.com/f497d1fbcf1c0919ba260ed64ac18829b3acf7a0
> > Cr-Commit-Position: refs/heads/master@{#319635}
>
> TBR=tommi@chromium.org
> NOPRESUBMIT=true
> NOTREECHECKS=true
> NOTRY=true
>
> Committed: https://crrev.com/62c6611787693f20f4201411d816d647f77f17d0
> Cr-Commit-Position: refs/heads/master@{#319638}

TBR=tommi@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/994603002

Cr-Commit-Position: refs/heads/master@{#319642}