Check Android API level when using usb.UsbDevice.getManufacturerName
android.hardware.usb.UsbDevice.getManufacturerName was added in API
level 21. This patch added code to check the API level to avoid
java.lang.NoSuchMethodError when testing pervious Android versions.

BUG=604634

Review URL: https://codereview.chromium.org/1898043003

Cr-Commit-Position: refs/heads/master@{#388294}
(cherry picked from commit 36d86338ea22decaa3a91eceb9a3dfdfbca2d40e)

Review URL: https://codereview.chromium.org/1952593003 .

Cr-Commit-Position: refs/branch-heads/2704@{#374}
Cr-Branched-From: 6e53600def8f60d8c632fadc70d7c1939ccea347-refs/heads/master@{#386251}