Revert of Remove create/delete methods from WebGraphicsContext3D. (patchset #6 id:100001 of https://codereview.chromium.org/1814263004/ )
Reason for revert:
FAILED: [snip]
../../third_party/WebKit/Source/platform/graphics/Canvas2DLayerBridge.cpp:255:27: error: unused variable 'webContext' [-Werror,-Wunused-variable]
    WebGraphicsContext3D* webContext = context();
                          ^
../../third_party/WebKit/Source/platform/graphics/Canvas2DLayerBridge.cpp:276:27: error: unused variable 'webContext' [-Werror,-Wunused-variable]
    WebGraphicsContext3D* webContext = context();
                          ^
2 errors generated.

Original issue's description:
> Remove create/delete methods from WebGraphicsContext3D.
>
> Have callers use the new Gen/Delete methods on GLES2Interface instead.
>
> R=bajones@chromium.org, chrishtr@chromium.org, kbr@chromium.org, pfeldman@chromium.org
> TBR=pfeldman
> BUG=584497
> CQ_INCLUDE_TRYBOTS=tryserver.chromium.win:win_optional_gpu_tests_rel
>
> Committed: https://crrev.com/d8fb03aaed3416b77589c154ae1e9c2c832bfa4b
> Cr-Commit-Position: refs/heads/master@{#382506}

TBR=chrishtr@chromium.org,bajones@chromium.org,kbr@chromium.org,pfeldman@chromium.org,piman@chromium.org,danakj@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=584497

Review URL: https://codereview.chromium.org/1817323003

Cr-Commit-Position: refs/heads/master@{#382507}