Revert of Make breakpad work in Mac GN. (patchset #1 id:1 of https://codereview.chromium.org/732853002/)
Reason for revert:
Ironically this broke the mac gn build:

http://build.chromium.org/p/chromium.mac/builders/Mac%20GN%20%28dbg%29/builds/608/steps/compile/logs/stdio

FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/breakpad/src/tools/mac/symupload/symupload.symupload.o.d -DCHROMIUM_BUILD -DV8_DEPRECATION_WARNINGS -DCLD_VERSION=2 -DENABLE_NOTIFICATIONS -DENABLE_PEPPER_CDMS -DENABLE_PLUGINS=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DUSE_OPENSSL=1 -DNO_TCMALLOC -DDISABLE_NACL -DENABLE_EXTENSIONS=1 -DENABLE_CONFIGURATION_POLICY -DENABLE_TASK_MANAGER=1 -DENABLE_THEMES=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_PLUGIN_INSTALLATION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_MANAGED_USERS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_WIFI_BOOTSTRAPPING=1 -DENABLE_REMOTING=1 -DENABLE_GOOGLE_NOW=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_HIDPI=1 -DCR_CLANG_REVISION=218707 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -I../../breakpad/src/common/mac -I../.. -Igen -fno-strict-aliasing -fstack-protector-all -arch i386 -fcolor-diagnostics -Wall -Wsign-compare -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wnewline-eof -Wno-c++11-narrowing -Wno-char-subscripts -Wno-covered-switch-default -Wno-deprecated-register -Wno-unneeded-internal-declaration -Wno-reserved-user-defined-literal -fvisibility=hidden -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.6.sdk -mmacosx-version-min=10.6 -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.dylib -Xclang -add-plugin -Xclang find-bad-constructs -Wheader-hygiene -Wstring-conversion -O0 -g2 -std=c99  -c ../../breakpad/src/tools/mac/symupload/symupload.m -o obj/breakpad/src/tools/mac/symupload/symupload.symupload.o
../../breakpad/src/tools/mac/symupload/symupload.m:85:18:error: unused function 'CompactIdentifier' [-Werror,-Wunused-function]
static NSString *CompactIdentifier(NSString *uuid) {
                 ^
1 error generated.

Original issue's description:
> Make breakpad work in Mac GN.
>
> R=brettw@chromium.org, thakis@chromium.org
> BUG=431177
>
> Committed: https://crrev.com/6ae55f928b690168c589912615894eb27cf62e1b
> Cr-Commit-Position: refs/heads/master@{#304884}

TBR=brettw@chromium.org,thakis@chromium.org,dpranke@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=431177

Review URL: https://codereview.chromium.org/725373006

Cr-Commit-Position: refs/heads/master@{#304888}