Revert of Switch components/password_manager code from IPC messages to Mojo. (patchset #28 id:550001 of https://codereview.chromium.org/1762603002/ )
Reason for revert:
Breaks Android GN (dbg) build. (Which is strange)
https://build.chromium.org/p/chromium.linux/builders/Android%20GN%20%28dbg%29/builds/20233

util.build_utils.CalledProcessError: Command failed: ( cd /b/build/slave/Android_GN__dbg_/build/src/out/Debug; javac -g -encoding UTF-8 -classpath lib.java/base/base_java.interface.jar:lib.java/mojo/public/java/bindings.interface.jar:lib.java/mojo/public/java/system.interface.jar -sourcepath '' -bootclasspath lib.java/android.interface.jar -source 1.7 -target 1.7 -Xlint:unchecked -Xlint:deprecation -d /tmp/tmpZ5Cfbk/classes /tmp/tmpZ5Cfbk/java/org/chromium/mojom/password_manager/mojom/CredentialManager.java /tmp/tmpZ5Cfbk/java/org/chromium/mojom/password_manager/mojom/CredentialManager_Internal.java /tmp/tmpZ5Cfbk/java/org/chromium/mojom/password_manager/mojom/CredentialType.java /tmp/tmpZ5Cfbk/java/org/chromium/mojom/password_manager/mojom/CredentialManagerError.java /tmp/tmpZ5Cfbk/java/org/chromium/mojom/password_manager/mojom/CredentialInfo.java )
/tmp/tmpZ5Cfbk/java/org/chromium/mojom/password_manager/mojom/CredentialInfo.java:37: error: package org.chromium.mojom.url.mojom does not exist
    public org.chromium.mojom.url.mojom.Origin federation;
                                       ^
/tmp/tmpZ5Cfbk/java/org/chromium/mojom/password_manager/mojom/CredentialInfo.java:205: error: package org.chromium.mojom.url.mojom does not exist
            result.federation = org.chromium.mojom.url.mojom.Origin.decode(decoder1);
                                                            ^
2 errors

Original issue's description:
> Switch components/password_manager code from IPC messages to Mojo.
>
> Replace credential_manager_messages.h IPC to Mojo service.
>
> BUG=582391
>
> Committed: https://crrev.com/d20fb918841354a75546fa38b5307aaba117598b
> Cr-Commit-Position: refs/heads/master@{#385369}

TBR=jochen@chromium.org,amistry@chromium.org,jam@chromium.org,rockot@chromium.org,sammc@chromium.org,tsepez@chromium.org,vabr@chromium.org,leon.han@intel.com
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=582391

Review URL: https://codereview.chromium.org/1861973002

Cr-Commit-Position: refs/heads/master@{#385371}