Revert of Avoid incorrect NC_AUTO_SUBFRAME renderer kills for non-web URLs. (patchset #1 id:1 of https://codereview.chromium.org/2111633002/ )
Reason for revert:
Sigh, test failed to compile on builder:

https://uberchromegw.corp.google.com/i/official.desktop.continuous/builders/win%20beta/builds/3447/steps/compile/logs/stdio

FAILED: obj/content/browser/frame_host/content_browsertests.navigation_controller_impl_browsertest.obj
ninja -t msvc -e environment.x86 -- "C:\b\depot_tools\win_toolchain\vs_files\95ddda401ec5678f15eeed01d2bee08fcbc5ee97\VC\bin\amd64_x86\cl.exe" /nologo /showIncludes /FC @obj\content\browser\frame_host\content_browsertests.navigation_controller_impl_browsertest.obj.rsp /c ..\..\content\browser\frame_host\navigation_controller_impl_browsertest.cc /Foobj\content\browser\frame_host\content_browsertests.navigation_controller_impl_browsertest.obj /Fdobj\content\content_browsertests.cc.pdb
c:\b\build\slave\win_beta\build\src\content\browser\frame_host\navigation_controller_impl_browsertest.cc(749): error C2664: 'bool content::ExecuteScript(const content::ToRenderFrameHost &,const std::string &)': cannot convert argument 1 from 'content::FrameTreeNode *' to 'const content::ToRenderFrameHost &'

Original issue's description:
> Avoid incorrect NC_AUTO_SUBFRAME renderer kills for non-web URLs.
>
> There are several corner cases with in-page navigations where non-web
> URLs (e.g., about:blank, file) may look cross-origin.  This was
> leading to renderer kills when a subframe went back/forward.
>
> A followup CL will account for these cases more accurately, but since
> this is just second line of defense against URL spoofs, we can loosen
> it to only check web URLs for the time being to avoid the kills.
>
> BUG=613732
> TEST=See bug comment 10 for repro steps.
> CQ_INCLUDE_TRYBOTS=tryserver.chromium.linux:linux_site_isolation
>
> Review-Url: https://codereview.chromium.org/2054013003
> Cr-Commit-Position: refs/heads/master@{#399228}
> (cherry picked from commit 37988b93bf48c3ef533f633fd74deee5b227c294)
>
> Committed: https://chromium.googlesource.com/chromium/src/+/38453aec59e45d2685bb327f3a9033554489e4e8

TBR=avi@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=613732

Review-Url: https://codereview.chromium.org/2110183003
Cr-Commit-Position: refs/branch-heads/2743@{#532}
Cr-Branched-From: 2b3ae3b8090361f8af5a611712fc1a5ab2de53cb-refs/heads/master@{#394939}