Revert 267422 because it broke compile on linux-clang buildbots.
The build failure:

sync/test/fake_server/fake_sync_server_http_handler.cc:51:61: error: too many arguments to function call, expected 2, have 3
                                                            &response);
                                                            ^~~~~~~~~
sync/test/fake_server/fake_server.h:44:3: note: 'HandleCommand' declared here
  void HandleCommand(const std::string& request,
  ^

> Use FakeServer-based invalidations for Sync tests
> 
> This CL creates a new InvalidationService implementation,
> FakeServerInvalidationService, to remove FakeServer-based tests'
> dependency on the Python XMPP server.
> 
> Another major change is that FakeServer's HandleCommand is now executed
> on the UI thread and locking has been removed from FakeServer itself.
> 
> BUG=323265
> 
> Review URL: https://codereview.chromium.org/234113002

TBR=pvalenzuela@chromium.org

Review URL: https://codereview.chromium.org/269643002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@267432 0039d316-1c4b-4281-b951-d872f2087c98