Revert of Fix use of 'sysroot' variable in harfbuzz.gyp (patchset #6 id:100001 of https://codereview.chromium.org/1151753002/)
Reason for revert:
Breaks GYP for Chrome OS builds. Repro steps:

 cros chrome-sdk --board=amd64-generic
 gclient runhooks

Updating projects from gyp files...
/bin/sh: /build/amd64-generic/build/bin/pkg-config: No such file or directory
gyp: Call to '/build/amd64-generic/build/bin/pkg-config --libs-only-l nss | sed -e "s/-lssl3//"' returned exit status 0.
/bin/sh: /build/amd64-generic/build/bin/pkg-config: No such file or directory
gyp: Call to '/build/amd64-generic/build/bin/pkg-config --libs libcras' returned exit status 127.
/bin/sh: /build/amd64-generic/build/bin/pkg-config: No such file or directory
gyp: Call to '/build/amd64-generic/build/bin/pkg-config --cflags x11' returned exit status 127.
Error: Command /usr/bin/python src/build/gyp_chromium returned non-zero exit status 1 in /ssd/src/chromium

TEST=cros chrome-sdk --board=amd64-generic && gclient runhooks

Original issue's description:
> Fix use of 'sysroot' variable in harfbuzz.gyp
>
> The sysroot variable is set conditionally in common.gypi
> but not at the nesting level required for other conditional
> to depend on it like the one in hardbuzz does.  This means
> that sysroot always appeared to be empty to harfbuzz.gyp,
> and hence the special handling for ARM linux was required.
>
> This change moves the setting of 'sysroot' up one level of
> nesting and defines 'pkg-config' in common.gypi so it can
> be shared.
>
> Committed: https://crrev.com/6a80b32f309490f44347f2925589a6f0fc23c3ff
> Cr-Commit-Position: refs/heads/master@{#331506}

TBR=mazda@chromium.org,dpranke@chromium.org,cpu@chromium.org,sbc@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/1154213004

Cr-Commit-Position: refs/heads/master@{#331642}