Revert 285657 "Move variations component code to variations name..."
Causes compile failures on official builders:
http://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20Win/builds/25600
http://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20ChromeOS/builds/70014

FAILED: ninja -t msvc -e environment.x86 -- c:\b\build\goma/gomacc "c:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64_x86\cl.exe" /nologo /showIncludes /FC @obj\chrome\browser\profile_resetter\browser_0.automatic_profile_resetter.obj.rsp /c ..\..\chrome\browser\profile_resetter\automatic_profile_resetter.cc /Foobj\chrome\browser\profile_resetter\browser_0.automatic_profile_resetter.obj /Fdobj\chrome\browser_0.cc.pdb 
c:\b\build\slave\google-chrome-rel-win\build\src\chrome\browser\profile_resetter\automatic_profile_resetter.cc(109) :error C2039: 'GetVariationParams' : is not a member of 'chrome_variations'
c:\b\build\slave\google-chrome-rel-win\build\src\chrome\browser\profile_resetter\automatic_profile_resetter.cc(109) :error C3861: 'GetVariationParams': identifier not found
ninja: build stopped: subcommand failed.

FAILED: /b/build/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/chrome/browser/profile_resetter/browser.automatic_profile_resetter.o.d -DV8_DEPRECATION_WARNINGS -DBLINK_SCALE_FILTERS_AT_RECORD_TIME -D_FILE_OFFSET_BITS=64 -DGOOGLE_CHROME_BUILD -DCR_CLANG_REVISION=209387 -DENABLE_RLZ -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_X11=1 -DUSE_XI2_MT=2 -DIMAGE_LOADER_EXTENSION=1 -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DUSE_PROPRIETARY_CODECS -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DENABLE_HIDPI=1 -DUSE_UDEV -DENABLE_EGLIMAGE=1 -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_PROD_WALLET_SERVICE=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DCLD2_DATA_SOURCE=static -DCLD_DATA_FROM_STATIC -DENABLE_FULL_PRINTING=1 -DENABLE_PRINTING=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_MANAGED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DNACL_WINDOWS=0 -DNACL_LINUX=1 -DNACL_OSX=0 -DNACL_ANDROID=0 -DNACL_TARGET_SUBARCH=64 -DNACL_TARGET_ARCH=x86 -DNACL_BUILD_SUBARCH=64 -DNACL_BUILD_ARCH=x86 -DFULL_SAFE_BROWSING -DGL_GLEXT_PROTOTYPES -DMOJO_USE_SYSTEM_IMPL -DLIBPEERCONNECTION_LIB=1 -DUSE_BRLAPI -DPROTOBUF_USE_DLLS -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DAUTOFILL_ENABLE_SYNC -DPASSWORD_MANAGER_ENABLE_SYNC '-DPRECACHE_CONFIG_SETTINGS_URL="http://www.gstatic.com/chrome/wifiprefetch/precache_config"' '-DPRECACHE_MANIFEST_URL_PREFIX="http://www.gstatic.com/chrome/wifiprefetch/precache_manifest_"' -DSK_ENABLE_INST_COUNT=0 -DSK_SUPPORT_GPU=1 '-DGR_GL_CUSTOM_SETUP_HEADER="GrGLConfig_chrome.h"' -DSK_ENABLE_LEGACY_API_ALIASING=1 -DSK_ATTR_DEPRECATED=SK_NOTHING_ARG1 -DGR_GL_IGNORE_ES3_MSAA=0 -DSK_WILL_NEVER_DRAW_PERSPECTIVE_TEXT -DSK_SUPPORT_LEGACY_PICTURE_CLONE -DSK_SUPPORT_LEGACY_GETDEVICE -DSK_IGNORE_ETC1_SUPPORT -DSK_IGNORE_GPU_DITHER -DSK_USE_POSIX_THREADS -DSK_DEFERRED_CANVAS_USES_FACTORIES=1 -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_STATIC_IMPLEMENTATION -DFEATURE_ENABLE_SSL -DFEATURE_ENABLE_VOICEMAIL -DEXPAT_RELATIVE_PATH -DGTEST_RELATIVE_PATH -DNO_MAIN_THREAD_WRAPPING -DNO_SOUND_SYSTEM -DLINUX -DPOSIX -DCHROMEOS -DLIBXML_STATIC '-DI18N_ADDRESS_VALIDATION_DATA_URL="https://i18napis.appspot.com/ssl-aggregate-address/"' -DI18N_ADDRESSINPUT_USE_BASICTYPES_OVERRIDE=1 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_LINUX -DWEBRTC_POSIX -DHUNSPELL_STATIC -DHUNSPELL_CHROME_CLIENT -DUSE_HUNSPELL -DRLZ_NETWORK_IMPLEMENTATION_CHROME_NET -DUSE_NSS=1 -DOS_CHROMEOS=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DOFFICIAL_BUILD -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -D_FORTIFY_SOURCE=2 -Igen -I../.. -Iobj/chrome/browser.gen -Iobj/chrome/browser.gen/chrome -I../../skia/config -I../../third_party/khronos -I../../gpu -I../../third_party/WebKit/Source -Igen/protoc_out -I../../third_party/protobuf -I../../third_party/protobuf/src -I../../third_party/dom_distiller_js/package/proto_gen -Igen/chrome -Igen/components/strings -I../../third_party/WebKit -I../../net/third_party/nss/ssl -I../../third_party/skia/src/core -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/pdf -I../../third_party/skia/include/gpu -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../skia/ext -I../../third_party/cacheinvalidation/overrides -I../../third_party/cacheinvalidation/src -I../../third_party/cacheinvalidation/google/cacheinvalidation -I../../third_party/icu/source/i18n -I../../third_party/icu/source/common -I../../third_party/libjingle/overrides -I../../third_party/libjingle/source -I../../third_party/webrtc/overrides -I../../testing/gtest/include -I../../third_party -I../../third_party/webrtc -I../../third_party/libxml/linux/include -I../../third_party/libxml/src/include -I../../third_party/zlib -Igen/ui/resources -Igen/ui/strings -I../../third_party/re2 -I../../third_party/leveldatabase/src/include -I../../third_party/leveldatabase/src -I../../third_party/leveldatabase -I../../third_party/libaddressinput/chromium/override -I../../third_party/libaddressinput/src/cpp/include -Igen/third_party/libaddressinput/ -I../../third_party/libyuv/include -I../../third_party/libyuv -I../../third_party/npapi -I../../third_party/npapi/bindings -Igen/ui/gl -I../../third_party/mesa/src/include -I../../v8/include -Igen/webkit -Igen/policy -Igen/ui/chromeos/resources -Werror -pthread -fno-exceptions -fno-strict-aliasing -Wall -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-reserved-user-defined-literal -Wno-deprecated-register -Xclang -load -Xclang /b/build/slave/google-chrome-rel-chromeos/build/src/tools/clang/scripts/../../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -fcolor-diagnostics -g -B/b/build/slave/google-chrome-rel-chromeos/build/src/third_party/binutils/Linux_x64/Release/bin -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/nss -I/usr/include/nspr -Wno-header-guard -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -Wexit-time-destructors -m64 -march=x86-64 -O2 -fdata-sections -ffunction-sections -fno-slp-vectorize -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -Wsign-compare -std=gnu++11  -c ../../chrome/browser/profile_resetter/automatic_profile_resetter.cc -o obj/chrome/browser/profile_resetter/browser.automatic_profile_resetter.o
../../chrome/browser/profile_resetter/automatic_profile_resetter.cc:109:3:error: no member named 'GetVariationParams' in namespace 'chrome_variations'; did you mean 'variations::GetVariationParams'?
  chrome_variations::GetVariationParams(kAutomaticProfileResetStudyName,
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  variations::GetVariationParams
../../components/variations/variations_associated_data.h:110:6: note: 'variations::GetVariationParams' declared here
bool GetVariationParams(const std::string& trial_name,
     ^
1 error generated.
ninja: build stopped: subcommand failed.

> Move variations component code to variations namespace.
> 
> BUG=284540
> TBR=sky@chromium.org, mathp@chromium.org
> 
> Review URL: https://codereview.chromium.org/412943002

TBR=asvitkine@chromium.org

Review URL: https://codereview.chromium.org/416333008

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@285675 0039d316-1c4b-4281-b951-d872f2087c98