aura_extra: component debug build fix
All modules including skia headers must depend on skia component.
../../third_party/skia/include/core/SkImageInfo.h:109: error: undefined reference to 'SkDebugf_FileLine(char const*, int, bool, char const*, ...)'
../../third_party/skia/include/core/SkString.h:22: error: undefined reference to 'SkDebugf_FileLine(char const*, int, bool, char const*, ...)'

Review URL: https://codereview.chromium.org/912293002

Cr-Commit-Position: refs/heads/master@{#315983}