Revert of mac: [Yosemite] Fix bug where zoom button causes fullscreen mode. (https://codereview.chromium.org/402443003/)
Reason for revert:
Broke Mac ASan 64 Builder
http://build.chromium.org/p/chromium.memory/builders/Mac%20ASan%2064%20Builder/builds/7520

obj/chrome/browser/ui/cocoa/browser_ui.version_independent_window.o
../../chrome/browser/ui/cocoa/version_independent_window.mm:109:44:error: cannot initialize a parameter of type 'NSComparisonResult (*)(id, id, void *)' with an rvalue of type 'int (*)(id, id, void *)': different return type ('NSComparisonResult' (aka 'long') vs 'int')
      [superview sortSubviewsUsingFunction:&ReorderContentViewToBack
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.6.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSView.h:175:75: note: passing argument to parameter 'compare' here
- (void)sortSubviewsUsingFunction:(NSComparisonResult (*)(id, id, void *))compare context:(void *)context;


Original issue's description:
> mac: [Yosemite] Fix bug where zoom button causes fullscreen mode.
> 
> In Yosemite, holding down alt while clicking the fullscreen button is supposed
> to zoom the window. This doesn't work because Chrome violates unstated AppKit
> assumptions.
> 
> The problem seems to lie in hit testing the location of the zoom button.
> Reordering the subviews by moving the tab strip and the content view behind the
> zoom button fixes the problem.
> 
> BUG=393808
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=284544

TBR=andresantoso@chromium.org,shess@chromium.org,erikchen@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=393808

Review URL: https://codereview.chromium.org/402323002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@284576 0039d316-1c4b-4281-b951-d872f2087c98