Revert "Update mojo sdk to rev d459e688a608f6eda850a23bb5e308a76ea51a47"
This reverts commit c4010b0b30bb37e0a6916c3fb8eb97d44b024292.

> Review URL: https://codereview.chromium.org/1051303002
> Cr-Commit-Position: refs/heads/master@{#324704}

It breaks the compile on Win8 GN dbg.

http://build.chromium.org/p/chromium.win/builders/Win8%20GN%20%28dbg%29/builds/4849

[870/2440] STAMP obj/cc/blink/cc_blink_unittests.inputdeps.stamp
[871/2440] STAMP obj/ui/snapshot/snapshot_unittests.inputdeps.stamp
[872/2440] ACTION //content/common:mojo_bindings__generator(//build/toolchain/win:32)
[873/2440] ACTION //content/common:mojo_bindings__generator(//build/toolchain/win:32)
[874/2440] ACTION //content/common:mojo_bindings__generator(//build/toolchain/win:32)
[875/2440] ACTION //content/common:mojo_bindings__generator(//build/toolchain/win:32)
[876/2440] ACTION //content/common:mojo_bindings__generator(//build/toolchain/win:32)
[877/2440] ACTION //third_party/mojo_services/src/gpu/public/interfaces:interfaces__generator(//build/toolchain/win:32)
[878/2440] ACTION //third_party/mojo_services/src/gpu/public/interfaces:interfaces__generator(//build/toolchain/win:32)
FAILED: ninja -t msvc -e environment.x86 -- E:\b\build\goma/gomacc.exe "E:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64_x86/cl.exe" /nologo /showIncludes /FC @obj/out/Debug/gen/third_party/mojo/src/mojo/public/interfaces/bindings/bindings.interface_control_messages.mojom.obj.rsp /c gen/third_party/mojo/src/mojo/public/interfaces/bindings/interface_control_messages.mojom.cc /Foobj/out/Debug/gen/third_party/mojo/src/mojo/public/interfaces/bindings/bindings.interface_control_messages.mojom.obj /Fdobj/third_party/mojo/src/mojo/public/interfaces/bindings/bindings_cc.pdb
e:\b\build\slave\win8_gn__dbg_\build\src\third_party\mojo\src\mojo\public\cpp\bindings\lib\array_internal.h(426) : error C2039: 'ArrayHeader' : is not a member of 'mojo::internal::internal'
        e:\b\build\slave\win8_gn__dbg_\b

TBR=rockot@chromium.org,jamesr@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=None

Review URL: https://codereview.chromium.org/1081543002

Cr-Commit-Position: refs/heads/master@{#324713}