Revert of Move ProfileSyncService away from listening for Signin notifications. (https://codereview.chromium.org/189163007/)
Reason for revert:
Broke compile on ChromeO:

FAILED: /b/build/goma/gomacc c++ -MMD -MF obj/chrome/browser/sync/unit_tests.profile_sync_service_startup_unittest.o.d -DV8_DEPRECATION_WARNINGS -DBLINK_SCALE_FILTERS_AT_RECORD_TIME -D_FILE_OFFSET_BITS=64 -DCHROMIUM_BUILD -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_NSS=1 -DUSE_X11=1 -DOS_CHROMEOS=1 -DUSE_XI2_MT=2 -DIMAGE_LOADER_EXTENSION=1 -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DUSE_PROPRIETARY_CODECS -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_INPUT_SPEECH -DENABLE_NOTIFICATIONS -DENABLE_HIDPI=1 -DENABLE_NEW_GAMEPAD_API=1 -DUSE_UDEV -DENABLE_EGLIMAGE=1 -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_AUTOMATION=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_FULL_PRINTING=1 -DENABLE_PRINTING=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_MANAGED_USERS=1 -DENABLE_MDNS=1 -DFULL_SAFE_BROWSING -DGL_GLEXT_PROTOTYPES -DUSE_BRLAPI -DLIBPEERCONNECTION_LIB=1 -DGTEST_HAS_POSIX_RE=0 -DPROTOBUF_USE_DLLS -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DNACL_WINDOWS=0 -DNACL_LINUX=1 -DNACL_OSX=0 -DNACL_TARGET_SUBARCH=64 -DNACL_TARGET_ARCH=x86 -DNACL_BUILD_SUBARCH=64 -DNACL_BUILD_ARCH=x86 -DAUTOFILL_ENABLE_SYNC -DUNIT_TEST -DGTEST_HAS_RTTI=0 -DCHROME_PNG_WRITE_SUPPORT -DPNG_USER_CONFIG -DSK_ENABLE_INST_COUNT=0 -DSK_SUPPORT_GPU=1 '-DGR_GL_CUSTOM_SETUP_HEADER="GrGLConfig_chrome.h"' -DSK_ENABLE_LEGACY_API_ALIASING=1 -DSK_ATTR_DEPRECATED=SK_NOTHING_ARG1 -DGR_GL_IGNORE_ES3_MSAA=0 -DSK_SUPPORT_LEGACY_LAYERRASTERIZER_API=1 -DSK_WILL_NEVER_DRAW_PERSPECTIVE_TEXT -DSK_SUPPORT_LEGACY_COMPATIBLEDEVICE_CONFIG=1 -DSK_SUPPORT_LEGACY_PUBLICEFFECTCONSTRUCTORS=1 -DSK_SUPPORT_LEGACY_COPYTO_CONFIG -DSK_SUPPORT_LEGACY_WRITEPIXELSCONFIG -DSK_SUPPORT_LEGACY_GETCLIPTYPE -DSK_SUPPORT_LEGACY_GETTOTALCLIP -DSK_USE_POSIX_THREADS -DSK_DEFERRED_CANVAS_USES_FACTORIES=1 -DU_USING_ICU_NAMESPACE=0 -DU_STATIC_IMPLEMENTATION -DLIBXML_STATIC '-DCUSTOM_BASICTYPES="base/basictypes.h"' '-DCUSTOM_SCOPED_PTR="base/memory/scoped_ptr.h"' -DFEATURE_ENABLE_SSL -DFEATURE_ENABLE_VOICEMAIL -DEXPAT_RELATIVE_PATH -DGTEST_RELATIVE_PATH -DNO_MAIN_THREAD_WRAPPING -DNO_SOUND_SYSTEM -DLINUX -DPOSIX -DCHROMEOS -DI18N_PHONENUMBERS_USE_ICU_REGEXP=1 -DI18N_PHONENUMBERS_NO_THREAD_SAFETY=1 -DHUNSPELL_STATIC -DHUNSPELL_CHROME_CLIENT -DUSE_HUNSPELL -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -D_FORTIFY_SOURCE=2 -I../.. -Igen/chrome -I../../third_party/khronos -I../../gpu -I../../skia/config -I../../third_party/WebKit/Source -Igen -Igen/protoc_out -I../../third_party/protobuf -I../../third_party/protobuf/src -Igen/components -I../../third_party/cacheinvalidation/google/cacheinvalidation -I../../testing/gmock/include -I../../testing/gtest/include -I../../third_party/WebKit -I../../third_party/npapi -I../../third_party/npapi/bindings -I../../third_party/libpng -I../../third_party/zlib -I../../third_party/libwebp -I../../third_party/ots/include -I../../third_party/qcms/src -I../../third_party/iccjpeg -I../../third_party/libjpeg -Igen/policy -I../../third_party/skia/src/core -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/pdf -I../../third_party/skia/include/gpu -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../skia/ext -I../../third_party/cacheinvalidation/overrides -I../../third_party/cacheinvalidation/src -I../../third_party/icu/source/i18n -I../../third_party/icu/source/common -I../../third_party/libxml/linux/include -I../../third_party/libxml/src/include -Igen/ui/ui_resources -Igen/components/strings -I../../third_party/leveldatabase/src/include -I../../third_party/leveldatabase/src -I../../third_party/leveldatabase -I../../third_party/libaddressinput/chromium/cpp/include -I../../third_party/libjingle/overrides -I../../third_party/libjingle/source -I../../third_party -I../../third_party/webrtc -Igen/protoc_out/third_party/libphonenumber -I../../third_party/libphonenumber/src -Igen/ui/gl -I../../third_party/mesa/src/include -I../../v8/include -Igen/webkit -Igen/ash/ash_resources -Igen/ash_strings -I../../net/third_party/nss/ssl -Werror -pthread -fno-exceptions -fno-strict-aliasing -Wall -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wno-unknown-pragmas -I/usr/include/nss -I/usr/include/nspr -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -Wsign-compare  -c ../../chrome/browser/sync/profile_sync_service_startup_unittest.cc -o obj/chrome/browser/sync/unit_tests.profile_sync_service_startup_unittest.o
../../chrome/browser/sync/profile_sync_service_startup_unittest.cc: In member function 'virtual void ProfileSyncServiceStartupTest_StartFirstTime_Test::TestBody()':
../../chrome/browser/sync/profile_sync_service_startup_unittest.cc:206:18: error: 'FakeSigninManagerForTesting' has no member named 'SignIn'
../../chrome/browser/sync/profile_sync_service_startup_unittest.cc: In member function 'virtual void ProfileSyncServiceStartupTest_DISABLED_StartNoCredentials_Test::TestBody()':
../../chrome/browser/sync/profile_sync_service_startup_unittest.cc:239:18: error: 'FakeSigninManagerForTesting' has no member named 'SignIn'
../../chrome/browser/sync/profile_sync_service_startup_unittest.cc: In member function 'virtual void ProfileSyncServiceStartupTest_DISABLED_StartInvalidCredentials_Test::TestBody()':
../../chrome/browser/sync/profile_sync_service_startup_unittest.cc:281:18: error: 'FakeSigninManagerForTesting' has no member named 'SignIn'
ninja: build stopped: subcommand failed.

Original issue's description:
> Move ProfileSyncService away from listening for Signin notifications.
> 
> As part of the effort to remove Signin-related notifications, move
> ProfileSyncService to observe the SigninManager instead.
> 
> BUG=345627
> R=zea@chromium.org
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=256213

TBR=zea@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=345627

Review URL: https://codereview.chromium.org/195053002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@256216 0039d316-1c4b-4281-b951-d872f2087c98