Revert of Restore previous input device to display pairing behavior. (patchset #1 id:1 of https://codereview.chromium.org/1689013004/ )
Reason for revert:
Reverting this and  https://codereview.chromium.org/1693663002
because  these changes failed to pass the M48 Chrome PFQ

Log Snippet :
chromeos-chrome-48.0.2564.110_rc-r1: ../../../../../../../home/chrome-bot/chrome_root/src/ash/touch/touchscreen_util.cc:47:41: error: 'class ash::DisplayInfo' has no member named 'sys_path' chromeos-chrome-48.0.2564.110_rc-r1:    if (!IsDeviceConnectedViaUsb(display->sys_path()) ||

Full log:
https://uberchromegw.corp.google.com/i/chromeos_release/builders/lumpy%20pre-flight%20release-R48-7647.B/builds/153/steps/BuildPackages/logs/stdio

Original issue's description:
> Restore previous input device to display pairing behavior.
>
> We want to always associate a input device so that we don't accidentally break
> anyone who is depending on this behavior.
>
> BUG=582516
>
> patch from issue 1652513002 at patchset 20001 (http://crrev.com/1652513002#ps20001)
>
> (cherry picked from commit d5c1e3b0b0a7b5b960ef16062d5722f24a1ea698)
>
> Committed: https://chromium.googlesource.com/chromium/src/+/bcd23e6e5da41158189a6e371e1834e4aac3bbc4

NOTRY=true
NOPRESUBMIT=true
TBR=jdufault@chromium.org
# Not skipping CQ checks because original CL landed more than 1 days ago.
BUG=582516

Review URL: https://codereview.chromium.org/1701103003

Cr-Commit-Position: refs/branch-heads/2564@{#693}
Cr-Branched-From: 1283eca15bd9f772387f75241576cde7bdec7f54-refs/heads/master@{#359700}