Revert 2 commits to fix an exception on the Android bots
This change reverts:
* "Generate a failing_results.json file." (commit 648ba37d33802486dea28cbad36d5b20765dfa70)
* "Stop generating and uploading incremental_results.json." (commit 68559d2c7e207041b0ac4bcc8e8636f647b6b00c)

which should fix the following error:

AttributeError: 'module' object has no attribute 'JSONResultsGeneratorBase'
(which was removed in commit 68559d2c7e207041b0ac4bcc8e8636f647b6b00c)

BUG=242206
TBR=ojan

Review URL: https://codereview.chromium.org/15473003

git-svn-id: svn://svn.chromium.org/blink/trunk@150678 bbb929c8-8fbe-4397-9dbb-9b2b20218538