Revert of Benchmark should validate that PageTest is used with telemetry.page.Page only. (patchset #2 id:20001 of https://codereview.chromium.org/800783004/)
Reason for revert:
Broke Win 7 Tests.

http://build.chromium.org/p/chromium.win/buildstatus?builder=Win%207%20Tests%20x64%20%281%29&number=19655
http://build.chromium.org/p/chromium.win/buildstatus?builder=Win%207%20Tests%20x64%20%281%29&number=19656
http://build.chromium.org/p/chromium.win/buildstatus?builder=Win7%20Tests%20%28dbg%29%281%29&number=33746

E:\b\depot_tools\python276_bin\python.exe E:\b\build\slave\Win7_Tests__dbg__1_\build\src\tools\telemetry\run_tests --browser debug --retry-limit 3 --write-full-results-to c:\users\chrome~2\appdata\local\temp\tmp52f8x2
Failed to import test module: telemetry.benchmark_unittest
Traceback (most recent call last):
  File "E:\b\depot_tools\python276_bin\lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "E:\b\depot_tools\python276_bin\lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "E:\b\build\slave\Win7_Tests__dbg__1_\build\src\tools\telemetry\telemetry\benchmark_unittest.py", line 37, in <module>
    class BenchmarkTest(unittest.TestCase):
AttributeError: 'module' object has no attribute 'TestCase'

Original issue's description:
> Benchmark should validate that PageTest is used with telemetry.page.Page only.
>
> BUG=439544
>
> Committed: https://crrev.com/0fba69c0bb29aafd637470a979e734eb5251a159
> Cr-Commit-Position: refs/heads/master@{#309161}

TBR=slamm@chromium.org,nednguyen@google.com,chrishenry@google.com
NOTREECHECKS=true
NOTRY=true
BUG=439544

Review URL: https://codereview.chromium.org/813253002

Cr-Commit-Position: refs/heads/master@{#309166}