media: build fix about CdmAdapter
clang complains it doesn't initialize const member, so this CL calls the
default constructor explicitly.

../../media/cdm/cdm_adapter.cc:638:32: error: default initialization of an object of const type 'const Decryptor::AudioFrames' (aka 'const list<scoped_refptr<media::AudioBuffer> >') without a user-provided default constructor
  const Decryptor::AudioFrames empty_frames;
                               ^
1 error generated

Review URL: https://codereview.chromium.org/1579493002

Cr-Commit-Position: refs/heads/master@{#368633}