Revert http://crrev.com/1365733005: Split captive portal metrics out of SSLErrorClassification
This reverts commit c0a91fac22f1d3ff3f8d052eb5dbffa70ef9835f.

android_clang_dbg_recipe bots failed compilation:
    http://build.chromium.org/p/tryserver.chromium.linux/builders/android_clang_dbg_recipe/builds/126886

    In file included from ../../chrome/browser/ssl/captive_portal_metrics_recorder.cc:5:
        ../../chrome/browser/ssl/captive_portal_metrics_recorder.h:43:8: error: private field 'captive_portal_detection_enabled_' is not used [-Werror,-Wunused-private-field]
          bool captive_portal_detection_enabled_;
               ^
        ../../chrome/browser/ssl/captive_portal_metrics_recorder.h:45:8: error: private field 'captive_portal_probe_completed_' is not used [-Werror,-Wunused-private-field]
          bool captive_portal_probe_completed_;
               ^
        ../../chrome/browser/ssl/captive_portal_metrics_recorder.h:47:8: error: private field 'captive_portal_no_response_' is not used [-Werror,-Wunused-private-field]
          bool captive_portal_no_response_;
               ^
        ../../chrome/browser/ssl/captive_portal_metrics_recorder.h:48:8: error: private field 'captive_portal_detected_' is not used [-Werror,-Wunused-private-field]
          bool captive_portal_detected_;
               ^
        4 errors generated.

BUG=n/a
NOTRY=true
TBR=felt@chromium.org

Review URL: https://codereview.chromium.org/1380513003

Cr-Commit-Position: refs/heads/master@{#351279}