Revert of [AppRemoting] Break out AppRemoting shared module (re-land). (patchset #2 id:20001 of https://codereview.chromium.org/1179873005/)
Reason for revert:
I believe this broke the linux GN clobber build:
https://build.chromium.org/p/chromium.linux/builders/Linux%20GN%20Clobber/builds/1309/steps/compile/logs/stdio

Traceback (most recent call last):
  File "../../remoting/webapp/build-webapp.py", line 487, in <module>
    sys.exit(main())
  File "../../remoting/webapp/build-webapp.py", line 483, in main
    return buildWebApp(**vars(args))
  File "../../remoting/webapp/build-webapp.py", line 257, in buildWebApp
    + buildtype + ': ' + service_environment)
Exception: Invalid service_environment targeted for Release:
ninja: build stopped: subcommand failed.

Original issue's description:
> [AppRemoting] Break out AppRemoting shared module.
>
> This is a reland of crrev.com/1176143002 with missing files added:
>   remoting/webapp/app_remoting/shared_module/manifest.json
>
> This cl breaks out the shared AppRemoting code into a shared module so
> that it does not need to be duplicated in each individual app.
>
> This version has the following limitations which will be addressed in
> follow-up cls:
> (1) The apps have a hard-coded reference to the dev shared module
> (2) The apps have a hard-coded reference to the dev orchestrator
> (3) The resources in the app stub should be replaced with empty stub
>     resources rather than a copy of all the shared resources.
> (4) The shared module is only built in GN (not GYP)
>
> BUG=
>
> Committed: https://crrev.com/5b696cf0d943d03a7bd388bdca1ffc6d95d3fc9c
> Cr-Commit-Position: refs/heads/master@{#334708}

TBR=kelvinp@chromium.org,thestig@chromium.org,garykac@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=

Review URL: https://codereview.chromium.org/1191883002

Cr-Commit-Position: refs/heads/master@{#334791}