Revert of Add POINTER_TYPE_ERASER to EventPointerType (patchset #5 id:80001 of https://codereview.chromium.org/2235933002/ )
Reason for revert:
Broke the build: https://build.chromium.org/p/chromium.chromiumos/builders/Linux%20ChromiumOS%20Builder/builds/45081/steps/compile/logs/stdio
../../ash/wm/stylus_metrics_recorder.cc:62:11: error: enumeration value 'POINTER_TYPE_ERASER' not handled in switch [-Werror,-Wswitch]

Original issue's description:
> Add POINTER_TYPE_ERASER to EventPointerType
>
> This pointer type can be used by graphics tablets, frequently the
> back-side of a stylus.
>
> BUG=636458
> TEST=Use rubber tool and watch generated mouse events.
>
> Committed: https://crrev.com/b90b789aea11dd97a7daa98bec8dd96d2f89f205
> Cr-Commit-Position: refs/heads/master@{#414146}

TBR=reveman@chromium.org,sadrul@chromium.org,spang@chromium.org,denniskempin@google.com
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=636458

Review-Url: https://codereview.chromium.org/2278033003
Cr-Commit-Position: refs/heads/master@{#414310}