Revert "Roll ANGLE 524e3bde19..6bd5831261"
Reason for revert:
This is causing compilation error on chromiumos builds.

bot/chrome_root/src/third_party/angle/src/common/debug.h:147:42: error: missing binary operator before token "("
chromeos-chrome-43.0.2337.0_alpha-r1:  #elif defined(__clang__) && __has_feature(cxx_static_assert)

see crbug.com/468139 for more detials.

>    Roll ANGLE 524e3bde19..6bd5831261
>
>    https://chromium.googlesource.com/angle/angle/+log/524e3bde19..6bd5831261
>
>    BUG=466735,466704
>
>    Review URL: https://codereview.chromium.org/1011213002
>
>    Cr-Commit-Position: refs/heads/master@{#320988}
BUG=466735,466704,468139
TBR=jmadill@chromium.org

Review URL: https://codereview.chromium.org/1009543005

Cr-Commit-Position: refs/heads/master@{#321055}