Fix missing dependency on Android gyp builds with mojo.
I hit this when building locally to reproduce another build error:
In file included from ../../content/browser/frame_host/frame_tree_node.h:16:0,
                 from ../../content/test/content_browser_test_utils_internal.cc:22:
../../content/browser/frame_host/render_frame_host_impl.h:34:68: fatal error: content/common/image_downloader/image_downloader.mojom.h: No such file or directory
 #include "content/common/image_downloader/image_downloader.mojom.h"

The problem is that content_browser_test_support target, which depends includes content_browser_test_utils_internal.cc, doesn't depend on content_browser on Android. It instead depends on content_app_both. content_app.gypi only had a direct dependency on the bindings, but needs an export dependency as well.

Review URL: https://codereview.chromium.org/1750823002

Cr-Commit-Position: refs/heads/master@{#378407}