Revert of delete the levelDB storage implementation. (patchset #5 id:80001 of https://codereview.chromium.org/1999443003/ )
Reason for revert:
This seems to be causing compile failures on Win x64 (at least this seems the only remotely plausible candidate...):

https://build.chromium.org/p/chromium/builders/Win%20x64/builds/925/steps/compile/logs/stdio

FAILED: obj/components/offline_pages/offline_pages.offline_page_storage_manager.obj
ninja -t msvc -e environment.x64 -- C:\b\build\slave\cache\cipd\goma/gomacc "C:\b\depot_tools\win_toolchain\vs_files\95ddda401ec5678f15eeed01d2bee08fcbc5ee97\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC @obj\components\offline_pages\offline_pages.offline_page_storage_manager.obj.rsp /c ..\..\components\offline_pages\offline_page_storage_manager.cc /Foobj\components\offline_pages\offline_pages.offline_page_storage_manager.obj /Fdobj\components\offline_pages.cc.pdb
c:\b\build\slave\win_x64\build\src\components\offline_pages\offline_page_storage_manager.cc(83): error C2220: warning treated as error - no 'object' file generated
c:\b\build\slave\win_x64\build\src\components\offline_pages\offline_page_storage_manager.cc(83): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
c:\b\build\slave\win_x64\build\src\base\bind_internal.h(186): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
c:\b\build\slave\win_x64\build\src\base\bind_internal.h(324): note: see reference to function template instantiation 'R base::internal::RunnableAdapter<T>::Run<offline_pages::OfflinePageStorageManager*,const offline_pages::OfflinePageStorageManager::ClearPageCallback&,const unsigned __int64&,_Ty>(Receiver &&,const offline_pages::OfflinePageStorageManager::ClearPageCallback &,const unsigned __int64 &,_Ty &&)' being compiled

Original issue's description:
> delete the levelDB storage implementation.
>
> BUG=NONE
>
> Committed: https://crrev.com/344bb7e95cb1619d98c15e1456c0044365e6c233
> Cr-Commit-Position: refs/heads/master@{#395371}

TBR=fgorski@chromium.org,dimich@chromium.org,bburns@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=NONE

Review-Url: https://codereview.chromium.org/2007523003
Cr-Commit-Position: refs/heads/master@{#395383}