Revert "Move core web_view code to extensions." (patchset #6 of https://codereview.chromium.org/496873006/)
This reverts commit 63bf863b12e8c2be593da2318af8ab7c7fbcc8a4.

This breaks the app_shell build for the reasons jamesr describes (src/extensions now depends on generated headers from src/chrome, but there cannot be a dependency from extensions -> chrome).

Hypothetical repro on Linux:
* rm -rf out/* && gclient runhooks && ninja -C out/Debug -j 1000 app_shell

chrome/browser/extensions/api/capture_web_contents_function.h:9:10: fatal error: 'chrome/common/extensions/api/types.h' file not found

Original issue's description:
> Move core web_view code to extensions.
>
>
> BUG=352290
>
> Committed: https://chromium.googlesource.com/chromium/src/+/1218a23163baab9f53d70e9a63030db13ef04d04

TBR=fsamuel@chromium.org,yoz@chromium.org,kalman@chromium.org,sky@chromium.org,dmazzoni@chromium.org,jamesr@chromium.org,hanxi@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=352290

Review URL: https://codereview.chromium.org/502273002

Cr-Commit-Position: refs/heads/master@{#291808}