Revert of tabing inconsistencies between trays in status area (patchset #3 id:40001 of https://codereview.chromium.org/2087703002/ )
Reason for revert:
I think this collided with https://codereview.chromium.org/2091933002/ and broke
the build:
c:\b\build\slave\win\build\src\ash\system\web_notification\web_notification_tray.cc(510):
error C3861: 'status_area_widget': identifier not found
https://build.chromium.org/p/chromium/buildstatus?builder=Win&number=44650

Original issue's description:
> Detailed reproduce steps are in comment 2 in crbug.com/468969
>
> There are several bugs in the status area tray focus advancing.
>
> (1) there is a invisible focus between system tray and web notification tray. This is because there is a focus traversal in web notification tray's child. Solution is to disable it.
> When virtual keyboard is enabled, we should also disable its child view traversal.
>
> (2) TAB will be trapped in system tray. Web notification tray is async painted. The initialization sibling relation may not be ready. Add a setnextfocusibleview call will fix that.
>
> BUG=468969
> TEST=tested on device, both tabing and shift-tabing works well on status area.
>
> There is still a bug in crbug.com/468969 comment 7. It happens in login screen only. When logged in, it works fine.
>
> Committed: https://crrev.com/133c792af9dfe8c82561bee7015efcc0b5dba22d
> Cr-Commit-Position: refs/heads/master@{#401765}

TBR=jennyz@chromium.org,warx@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=468969

Review-Url: https://codereview.chromium.org/2090353005
Cr-Commit-Position: refs/heads/master@{#401784}