Revert of [android] Remove libaddressinput Java widget. (patchset #1 id:1 of https://codereview.chromium.org/890103002/)
Reason for revert:
This CL broke the gn android build.

To reproduce locally on a chromium checkout src:

> gn gen --args='os="android" cpu_arch="arm" use_goma=true' out_android_gn/Debug
> ninja -C out_android_gn/Debug

eventually fails with:

[6011/25521] CXX obj/third_party/libaddressinput/chromium/libaddressinput.chrome_address_validator.o
<snip>
../../third_party/libaddressinput/chromium/chrome_address_validator.cc:156:68: error: call of overloaded 'pow(int, int)' is ambiguous
       GetBaseRetryPeriod() * pow(2, attempts_number_[region_code]++));

Original issue's description:
> [android] Remove libaddressinput Java widget.
>
> Android uses a custom UI with the cross-platform strings for address
> input.
>
> BUG=454120
>
> Committed: https://crrev.com/e7e8b5f5a53c3577b84413bd165731ca66d6a837
> Cr-Commit-Position: refs/heads/master@{#314217}

TBR=estade@chromium.org,cpu@chromium.org,rouslan@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=454120

Review URL: https://codereview.chromium.org/892403002

Cr-Commit-Position: refs/heads/master@{#314325}