Fix compilation of net_unittests with Xcode 7 (OS X 10.11 SDK).
With Xcode 7 and OS X 10.11 SDK, the SecKeychainEvent enumeration has
new value, causing a compilation failure in the switch as some values
are not caught. Fix this by using a default clause.

Fixes the following error:
../../net/cert/cert_database_mac.cc:104:11: error: 8 enumeration values not handled in switch: 'kSecLockEvent', 'kSecUnlockEvent', 'kSecAddEvent'... [-Werror,-Wswitch]
  switch (keychain_event) {

BUG=517914

Review URL: https://codereview.chromium.org/1340463002

Cr-Commit-Position: refs/heads/master@{#348904}