[Temp][Android] M48 gardening: Partially revert a change to make gyp_xwalk work
This partially reverts the https://codereview.chromium.org/1428173002
which caused the gyp_xwalk to break with following error message,
Exception: 'build' is not in list
Traceback (most recent call last):
  File "/home/mrunal/xwalk/src/tools/gyp/pylib/gyp/input.py", line 491, in CallLoadTargetBuildFile
    includes, depth, check, False)
  File "/home/mrunal/xwalk/src/tools/gyp/pylib/gyp/input.py", line 412, in LoadTargetBuildFile
    build_file_data, PHASE_EARLY, variables, build_file_path)
  File "/home/mrunal/xwalk/src/tools/gyp/pylib/gyp/input.py", line 1287, in ProcessVariablesAndConditionsInDict
    build_file)
  File "/home/mrunal/xwalk/src/tools/gyp/pylib/gyp/input.py", line 1302, in ProcessVariablesAndConditionsInList
    ProcessVariablesAndConditionsInDict(item, phase, variables, build_file)
  File "/home/mrunal/xwalk/src/tools/gyp/pylib/gyp/input.py", line 1287, in ProcessVariablesAndConditionsInDict
    build_file)
  File "/home/mrunal/xwalk/src/tools/gyp/pylib/gyp/input.py", line 1302, in ProcessVariablesAndConditionsInList
    ProcessVariablesAndConditionsInDict(item, phase, variables, build_file)
  File "/home/mrunal/xwalk/src/tools/gyp/pylib/gyp/input.py", line 1287, in ProcessVariablesAndConditionsInDict
    build_file)
  File "/home/mrunal/xwalk/src/tools/gyp/pylib/gyp/input.py", line 1306, in ProcessVariablesAndConditionsInList
    expanded = ExpandVariables(item, phase, variables, build_file)
  File "/home/mrunal/xwalk/src/tools/gyp/pylib/gyp/input.py", line 886, in ExpandVariables
    replacement = str(py_module.DoMain(parsed_contents[1:])).rstrip()
  File "/home/mrunal/xwalk/src/build/android/gyp/java_cpp_enum.py", line 340, in DoMain
    for output_path, data in DoGenerate(args[1:]):
  File "/home/mrunal/xwalk/src/build/android/gyp/java_cpp_enum.py", line 249, in DoGenerate
    output = GenerateOutput(source_path, enum_definition)
  File "/home/mrunal/xwalk/src/build/android/gyp/java_cpp_enum.py", line 290, in GenerateOutput
    'SCRIPT_NAME': GetScriptName(),
  File "/home/mrunal/xwalk/src/build/android/gyp/java_cpp_enum.py", line 233, in GetScriptName
    build_index = script_components.index('build')
ValueError: 'build' is not in list