Revert of Roll breakpad a513e85:7caf028 (svn 1384:1385) (patchset #1 id:1 of https://codereview.chromium.org/590403003/)
Reason for revert:
Broke TSANv2 builder:

breakpad/src/client/linux/minidump_writer/minidump_writer.cc:554:37: error: use of undeclared identifier 'time'
    header.get()->time_date_stamp = time(NULL);

Original issue's description:
> Roll breakpad a513e85:7caf028 (svn 1384:1385)
>
> r1385: Linux: Call memset() in a couple places in ExceptionHandler.
>
> BUG=332335
>
> Committed: https://crrev.com/ec86bac94da60dc9286bb49b87745570a83a6a55
> Cr-Commit-Position: refs/heads/master@{#296446}

TBR=timurrrr@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=332335

Review URL: https://codereview.chromium.org/595343003

Cr-Commit-Position: refs/heads/master@{#296459}