Fix cras_input_unittests with component=shared_library
This adds a missing export required by tests:

../../media/audio/cras/cras_input_unittest.cc:80: error: undefined reference to 'media::CrasInputStream::CrasInputStream(media::AudioParameters const&, media::AudioManagerCras*, std::string const&)'

BUG=none
TEST=cros chrome-sdk --board=link
  GYP_DEFINES="$GYP_DEFINES component=shared_library" gclient runhooks
  ninja -C out_link/Release

Review URL: https://codereview.chromium.org/1211003004

Cr-Commit-Position: refs/heads/master@{#336279}