Revert 273599 "Cast: Synthetic benchmark tool."
Broke win compile.
c:\b\build\slave\win_x64_builder__dbg_\build\src\media\cast\test\utility\test_util.cc(25) : error C2039: 'max' : is not a member of 'std'


> Cast: Synthetic benchmark tool.
> 
> This benchmark tests how much latency, packet loss and bandwidth loss we can tolerate.
> It runs hundreds of times faster than real-time and results are independent of CPU speed.
> So far, it does a series of binary searches to find a spanning tree of the space in which
> our algorithms can operate comfortably.
> 
> Review URL: https://codereview.chromium.org/293173002

TBR=hubbe@chromium.org

Review URL: https://codereview.chromium.org/301313002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@273612 0039d316-1c4b-4281-b951-d872f2087c98