Revert of Linux: Sort installer expectations in ASCII order. (patchset #2 id:20001 of https://codereview.chromium.org/1644313002/ )
Reason for revert:
Potentially caused Google Chrome Linux [x64] compile failures:
https://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20Linux/builds/45191
https://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20Linux%20x64/builds/7808

FAILED: cd ../../chrome; flock -- /tmp/linux_package_lock bash ../out/Release/installer/rpm/build.sh -o../out/Release -b ../out/Release -a ia32 -d google_chrome -c beta
...
ERROR: Shared library dependencies changed!
If this is intentional, please update:
chrome/installer/linux/rpm/expected_deps_i386
chrome/installer/linux/rpm/expected_deps_x86_64

Original issue's description:
> Linux: Sort installer expectations in ASCII order.
>
> Committed: https://crrev.com/e54ba1f2b08f887f1a0e8898d2dc0904bacb38c4
> Cr-Commit-Position: refs/heads/master@{#372802}

TBR=phajdan.jr@chromium.org,mmoss@chromium.org,thestig@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/1652373002

Cr-Commit-Position: refs/heads/master@{#372845}