Revert of Blink roll 171141:171171 (https://codereview.chromium.org/231713002/)
Reason for revert:
Compile errors on chromiumos builder [multiple cycles] due to 

https://src.chromium.org/viewvc/blink?revision=171165&view=revision

/third_party/WebKit/Source/core/dom/CharacterData.cpp:146:36:
error: 'realCount' may be used uninitialized in this function
[-Werror=maybe-uninitialized]
chromeos-chrome-36.0.1933.0_alpha-r1:      newStr.remove(offset, realCount);

link: http://build.chromium.org/p/chromium.chromiumos/builders/ChromiumOS%20%28x86%29/builds/20955

Original issue's description:
> Blink roll 171141:171171
> 
> http://build.chromium.org/f/chromium/perf/dashboard/ui/changelog_blink.html?url=/trunk&range=171141:171171&mode=html
> TBR=
> BUG=
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=262863

TBR=yurys@chromium.org,jianli@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=

Review URL: https://codereview.chromium.org/232443002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@262905 0039d316-1c4b-4281-b951-d872f2087c98