IWYU: ffloor(3) needs <cmath>.
This fixes the build with recent libstdc++ versions (mine is at 6.1.1),
which do not implicitly include <cmath> and cause the build to fail like
this after commit af57af3079ddbb21be992e839023ff6e45ec6ef4 ("Video Color
Managament"):

../cc/output/color_lut_cache.cc:36:46: error: use of undeclared identifier 'floorf'

R=hubbe@chromium.org,ccameron@chromium.org,danakj@chromium.org
BUG=622133
CQ_INCLUDE_TRYBOTS=master.tryserver.blink:linux_precise_blink_rel

Review-Url: https://codereview.chromium.org/2238243002
Cr-Commit-Position: refs/heads/master@{#411798}