Revert of Use Mojo pipes to signal sync IPC events (patchset #30 id:760001 of https://codereview.chromium.org/2033243003/ )
Reason for revert:
Breaks DrMemory builder. Sorry:

https://build.chromium.org/p/chromium.memory.fyi/builders/Chromium%20Windows%20Builder%20%28DrMemory%29?numbuilds=200

First breaking build:

https://build.chromium.org/p/chromium.memory.fyi/builders/Chromium%20Windows%20Builder%20%28DrMemory%29/builds/17216

Error:

Updating projects from gyp files...

Exception: Unknown AST node at key path 'includes': Set([Const('mojo_public.gypi')]) while reading C:\b\build\slave\drm-cr\build\src\mojo\mojo_public.gyp

Traceback (most recent call last):

  File "C:\b\build\slave\drm-cr\build\src\tools\gyp\pylib\gyp\input.py", line 496, in CallLoadTargetBuildFile

    includes, depth, check, False)

  File "C:\b\build\slave\drm-cr\build\src\tools\gyp\pylib\gyp\input.py", line 391, in LoadTargetBuildFile

    includes, True, check)

  File "C:\b\build\slave\drm-cr\build\src\tools\gyp\pylib\gyp\input.py", line 240, in LoadOneBuildFile

    build_file_data = CheckedEval(build_file_contents)

  File "C:\b\build\slave\drm-cr\build\src\tools\gyp\pylib\gyp\input.py", line 194, in CheckedEval

    return CheckNode(c3[0], [])

  File "C:\b\build\slave\drm-cr\build\src\tools\gyp\pylib\gyp\input.py", line 210, in CheckNode

    dict[key] = CheckNode(c[n + 1], kp)

  File "C:\b\build\slave\drm-cr\build\src\tools\gyp\pylib\gyp\input.py", line 224, in CheckNode

    "': " + repr(node))

TypeError: Unknown AST node at key path 'includes': Set([Const('mojo_public.gypi')]) while reading C:\b\build\slave\drm-cr\build\src\mojo\mojo_public.gyp

Original issue's description:
> Use Mojo pipes to signal sync IPC events
>
> This transitions legacy sync IPC to use Mojo message pipe handles
> for all of its sync event waiting. This is a necessary precursor to
> mixing sync legacy IPC with sync Mojo IPC, and is also required to
> support correct FIFO between ChannelProxy and Mojo Channel
> associated interfaces.
>
> Specifically:
>
>  - Introduces a new IPC::MojoEvent type which is a WaitableEvent-like
>    interface around a local message pipe.
>  - Moves mojo::SyncHandleRegistry out of internal bindings API and
>    exposes it publicly.
>  - Replaces most uses of WaitableEvent with MojoEvent for sync IPC
>  - Replaces all use of WaitableEvent::WaitMany for sync IPC
>    with mojo::SyncHandleRegistry::WatchAllHandles.
>  - Cleans up some unnecessary complexity in SyncMessage since
>    pump_messages_event() was only being used with a single
>    global event that's always signaled.
>
> The system's behavior should be effectively unchanged by this CL,
> but legacy sync IPC and mojo sync IPC can now be mixed freely.
>
> BUG=612500
> CQ_INCLUDE_TRYBOTS=tryserver.chromium.linux:linux_optional_gpu_tests_rel;tryserver.chromium.mac:mac_optional_gpu_tests_rel;tryserver.chromium.win:win_optional_gpu_tests_rel
>
> Committed: https://crrev.com/97912711c72d91e50bf6999f6842f9de1c05fab1
> Cr-Commit-Position: refs/heads/master@{#399848}

TBR=bbudge@chromium.org,jam@chromium.org,mseaborn@chromium.org,raymes@chromium.org,sievers@chromium.org,yzshen@chromium.org,rockot@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=612500

Review-Url: https://codereview.chromium.org/2067233002
Cr-Commit-Position: refs/heads/master@{#399905}