Revert of DevTools: extract V8DebuggerAgent interface, move it under .../inspector/v8 (patchset #5 id:80001 of https://codereview.chromium.org/1367623006/ )
Reason for revert:
Broke oilpan:

In file included from gen/blink/core/InspectorInstrumentationImpl.cpp:10:
../../third_party/WebKit/Source/core/inspector/AsyncCallTracker.h:58:5: error: only virtual member functions can be marked 'override'
    WILL_BE_USING_GARBAGE_COLLECTED_MIXIN(AsyncCallTracker);
    ^
../../third_party/WebKit/Source/platform/heap/GarbageCollected.h:210:53: note: expanded from macro 'WILL_BE_USING_GARBAGE_COLLECTED_MIXIN'
#define WILL_BE_USING_GARBAGE_COLLECTED_MIXIN(TYPE) USING_GARBAGE_COLLECTED_MIXIN(TYPE)
                                                    ^
../../third_party/WebKit/Source/platform/heap/GarbageCollected.h:199:5: note: expanded from macro 'USING_GARBAGE_COLLECTED_MIXIN'
    DEFINE_GARBAGE_COLLECTED_MIXIN_METHODS(blink::Visitor*, TYPE)       \
    ^
../../third_party/WebKit/Source/platform/heap/GarbageCollected.h:134:47: note: expanded from macro 'DEFINE_GARBAGE_COLLECTED_MIXIN_METHODS'
    void adjustAndMark(VISITOR visitor) const override

Original issue's description:
> DevTools: extract V8DebuggerAgent interface, move it under .../inspector/v8
>
> V8DebuggerAgent was split into interface and implementation. All other agents should depend on the public part only.
>
> Once InjectedScript, InjectedScriptHost and InjectedScriptManager are also moved to .../inspector/v8 some of the methods on V8DebuggerAgent will be removed and called only by the implementation classes.
>
> BUG=439376
>
> Committed: https://crrev.com/80862359ba867d2807e9ba7b366b352ee5cfda2b
> Cr-Commit-Position: refs/heads/master@{#351166}

TBR=dgozman@chromium.org,pfeldman@chromium.org,yurys@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=439376

Review URL: https://codereview.chromium.org/1370373004

Cr-Commit-Position: refs/heads/master@{#351228}