Prevent calling slow children when fast alternatives are available.
This patch makes slow{First,Last}Child WTF_DELETED_FUNCTION for
classes that have a fast {first,last}Child implementation available.
Calling slowFirstChild() on RenderBlock will now result in a compile
failure:
error: attempt to use a deleted function
    const RenderObject* renderer = block->slowFirstChild();

This patch caught FastTextAutosizer using slowFirstChild unnecessarily.

No new tests as there should be no observable change in behavior.

Review URL: https://codereview.chromium.org/299863005

git-svn-id: svn://svn.chromium.org/blink/trunk@174655 bbb929c8-8fbe-4397-9dbb-9b2b20218538