Revert of Associate UDL input devices with their corresponding displays. (patchset #1 id:1 of https://codereview.chromium.org/1693663002/ )
Reason for revert:
This broke M48 Chrome PFQ

Log Snippet :
chromeos-chrome-48.0.2564.110_rc-r1: ../../../../../../../home/chrome-bot/chrome_root/src/ash/touch/touchscreen_util.cc:47:41: error: 'class ash::DisplayInfo' has no member named 'sys_path' chromeos-chrome-48.0.2564.110_rc-r1:    if (!IsDeviceConnectedViaUsb(display->sys_path()) ||

Full log:
https://uberchromegw.corp.google.com/i/chromeos_release/builders/lumpy%20pre-flight%20release-R48-7647.B/builds/153/steps/BuildPackages/logs/stdio

NOTRY=true
NOPRESUBMIT=true

Original issue's description:
> Associate UDL input devices with their corresponding displays.
>
> This CL completely rewrites display/touchscreen association code. There were a
> lot of hidden/tricky gotchas and the rewrite calls them out. The association
> logic is also significantly easier to extend.
>
> UDL assocation logic is added using the path to the input/display devices. The
> code that exposes the device paths is in two dependent CLs.
>
> BUG=543209
>
> Review URL: https://codereview.chromium.org/1508203002
>
> Cr-Commit-Position: refs/heads/master@{#368773}
> (cherry picked from commit 10215fdb245b735fd0194f0c24e45d2734a5918a)
>
> Committed: https://chromium.googlesource.com/chromium/src/+/05a1e94ef976f7e065a0e7b350f6cb566b839010

TBR=jdufault@chromium.org
# Not skipping CQ checks because original CL landed more than 1 days ago.
BUG=543209

Review URL: https://codereview.chromium.org/1709453002

Cr-Commit-Position: refs/branch-heads/2564@{#694}
Cr-Branched-From: 1283eca15bd9f772387f75241576cde7bdec7f54-refs/heads/master@{#359700}