Revert of Add "magic values" to HTMLFrameOwnerElement and Frame to help diagnose crash (patchset #2 id:20001 of https://codereview.chromium.org/1369003003/ )
Reason for revert:
Broke oilpan:

../../third_party/WebKit/Source/core/html/HTMLFrameOwnerElement.cpp:175:21: error: [blink-gc] Finalizer '~HTMLFrameOwnerElement' accesses potentially finalized field 'm_contentFrame'.
    RELEASE_ASSERT(!m_contentFrame);
                    ^
../../third_party/WebKit/Source/core/html/HTMLFrameOwnerElement.h:105:5: note: [blink-gc] Potentially finalized field 'm_contentFrame' declared here:
    RawPtrWillBeMember<Frame> m_contentFrame;
    ^
../../third_party/WebKit/Source/platform/heap/Handle.h:923:28: note: expanded from macro 'RawPtrWillBeMember'
#define RawPtrWillBeMember blink::Member

Original issue's description:
> Add "magic values" to HTMLFrameOwnerElement and Frame to help diagnose crash
>
> I've narrowed down the linked crash to a bad m_owner pointer in Frame. I've
> added two temporary magic values to help diagnose where this is coming from:
>
> In Frame I added a magic value beside the m_owner element to guard against
> heap corruption.
>
> In HTMLFrameOwnerElement I added a magic value that should help us catch when
> m_owner is not pointing to an HTMLFrameOwnerElement sooner.
>
> In both cases, we should also be able to see if either m_owner of Frame has
> already been destructed.
>
> Also turned the ASSERT in ~HTMLFrameOwnerElement into a RELEASE_ASSERT in
> case we're destroying it without disconnecting it from the Frame.
>
> BUG=519752
>
> Committed: https://crrev.com/ed993a4bbebc7f3305a639a343ef5d461eb64e69
> Cr-Commit-Position: refs/heads/master@{#351150}

TBR=rbyers@chromium.org,bokan@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=519752

Review URL: https://codereview.chromium.org/1373143003

Cr-Commit-Position: refs/heads/master@{#351230}