Revert "Merge to M52: Record offline histograms with suffix via Histogram::FactoryGet"
This reverts commit b58f3022768966477a16419348780ed8c1fa42f0.

Causing compilation failures:

../../components/offline_pages/offline_page_metadata_store_impl.cc: In member function 'void offline_pages::OfflinePageMetadataStoreImpl::LoadDone(const LoadCallback&, bool, std::__1::unique_ptr<std::__1::vector<offline_pages::OfflinePageEntry> >)':
../../components/offline_pages/offline_page_metadata_store_impl.cc:177:37: error: 'kBookmarkNamespace' is not a member of 'offline_pages'
         item.client_id.name_space = offline_pages::kBookmarkNamespace;

BUG=616231

Cr-Commit-Position: refs/branch-heads/2743@{#229}
Cr-Branched-From: 2b3ae3b8090361f8af5a611712fc1a5ab2de53cb-refs/heads/master@{#394939}